#!/bin/bash

for patch in *.patch
do
	[ -f "$patch.trigger" ] && continue
	
	{
		cat - <<'EOF'
#!/bin/bash

patch="${0%.trigger}"
series="$1"
build="$2"

EOF
		awk '/^TRIGGER/ { print "file=\"" $3 "\""; print "csum=\"" $2 "\"" }' "$patch"
		cat - <<'EOF'
file_csum=$( md5sum "$file" | awk '{print $1}' )
if [ "$file_csum" = "$csum" ]; then
	echo "*** applying $patch ..."
	git am "$patch"
fi
EOF
	} >"$patch.trigger"
done
