pipeline:
  - ktl

jobs:
  ktl:
    matrix:
      # Our minimum Python version is 3.6.9
      - series: bionic
      - series: focal
      - series: jammy
    architectures: amd64
    packages:
      - python3
      - python3-testfixtures
      - python3-yaml
    run: cd ktl && python3 -m unittest -v
