#!/bin/sh

here=$(dirname "$(readlink -f "${0}")")

if [ "$1" = '--update' ]; then
	# Update ourselves, that may include this script so ensure
	# we use the new version.
	shift
	cd "$here" || exit 1
	echo "II: updating kteam-tools"
	git pull
	exec "$here/deploy" --update-deps "$@"
fi

update=
if [ "$1" = '--update-deps' ]; then
	update=1
fi

while read thing url
do
	dep="deps/$thing"
	mkdir -p "$dep"
	if [ ! -d "$dep/.git" ]; then
		echo "II: cloning dependency $thing ($url)"
		git clone "$url" "$dep"

	elif [ -n "$update" ]; then
		echo "II: updating dependency $thing ($url)"
		(cd "$dep" && git pull)
	fi
done <<EOL
so-trello	git://git.launchpad.net/~apw/+git/so-trello
EOL

ln -sf $(realpath --relative-to=stable deps/so-trello/trellotool) stable/trellotool
