#!/bin/sh

here=$(dirname "$(readlink -f "${0}")")
app=$(basename "$here")

if [ "$1" = '--update' ]; then
	# Update ourselves, that may include this script so ensure
	# we use the new version.
	shift
	cd "$here" || exit 1
	echo "II: updating $app"
	git pull --ff-only || exit 1
	exec "$here/deploy" --update-deps "$@"
fi

update=
if [ "$1" = '--update-deps' ]; then
	update=1
fi

DEPLOY_DEPS="${DEPLOY_DEPS:-deps}"
while read thing url master
do
	dep="$DEPLOY_DEPS/$thing"
	mkdir -p "$dep"
	if [ ! -d "$dep/.git" ]; then
		echo "II: $app: cloning dependency $thing ($url)"
		git clone "$url" "$dep"

	elif [ -n "$update" ]; then
		echo "II: $app: updating dependency $thing ($url)"
		(
			cd "$dep" || exit 1
			if [ -x "./deploy" ]; then
				DEPLOY_DEPS=".." "./deploy" --update
			else
				git pull --ff-only
			fi
		)
	fi
done <<EOL
so-trello			git://git.launchpad.net/~apw/+git/so-trello
python-mattermost-driver	git://git.launchpad.net/~canonical-kernel-team/+git/python-mattermost-driver https://github.com/Vaelor/python-mattermost-driver
python-jira			git://git.launchpad.net/~canonical-kernel-team/+git/python-jira  https://github.com/pycontribs/jira
EOL

ln -sf $(realpath --relative-to=stable $DEPLOY_DEPS/so-trello/trellotool) stable
ln -sf $(realpath --relative-to=stable $DEPLOY_DEPS/python-jira/jira) stable

ln -sf $(realpath --relative-to=announce $DEPLOY_DEPS/python-mattermost-driver/src/mattermostdriver) announce
ln -sf $(realpath --relative-to=announce $DEPLOY_DEPS/python-jira/jira) announce
