# kteam-tools is not an installable project. We use
# this file to control our dependencies and linter
# configurations all in one place.
[project]
name = "kteam-tools"
requires-python = ">=3.8"
readme = "README"
version = "0.0.1"
dependencies = [
  "python-apt @ git+https://salsa.debian.org/apt-team/python-apt.git@2.8.0",
  "python-dateutil",
  "python-debian",
  "pyyaml",
  "xdg",
]

# Modules will be managed separately (cranky, info, ktl, etc.)
[tool.setuptools]
py-modules = []

[project.optional-dependencies]
dev = [
  "black",
  "pre-commit",
  "pytest",
  "ruff",
  "testfixtures",
]

[tool.black]
# Must match [tool.ruff.line-length]
line-length = 120

# Emit code compatible with this minimum version
target-version = ["py38"]

# One mega regex
exclude = '''
(
  /(
    | \.git
    | \.venv
    | dist
  )
)
'''

[tool.ruff]
# Literal paths and globbing are supported
exclude = [
    ".git",
    ".ruff_cache",
    "venv",
]

# https://beta.ruff.rs/docs/settings/#extend-per-file-ignores
per-file-ignores = {}

# Must match [tool.black.line-length]
line-length = 120

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Code generated by --fix will be compatible with this version
target-version = "py38"

[tool.pytest.ini_options]
testpaths = [
    "cranky/crl/tests",
    "cranky/annotations-tools/tests",
    "stable/wfl/tests",
    "adt-matrix/tests",
    "ktl/tests",
    "dashboard/ktml/tests",
]
