#!/bin/bash

case "$1" in
kernel-uploads)
    (cd /srv/kernel.ubuntu.com/www/kpi/kernel-uploads  &&
    "$HOME/kteam-tools/kpi/kernel-uploads/kernel-uploads" >kernel-uploads.txt &&
    curl -i -XPOST 'http://influxdb.cloud.kpi.internal:8086/write?db=kernel' --data-binary '@kernel-uploads.txt' --netrc-file $HOME/.influx-kernel.auth)
    ;;
esac
