#!/bin/sh

set +x
set -e

echo "  Stage 2:"
echo "    . Verify packages built and create derivative tracking bugs"

# This is the first turn of the crank. The packages should be
# all built in the ppa and ready to go to -proposed. See if
# sru-workflow-manager comes to that same conclusion.
#
../swm --staging --dryrun-email --verbose > 2.log 2>&1

./tracking-bugs-snapshot snap-stage2
./tracking-bugs-verify ref-tbs-stage2 snap-stage2

../swm --staging --dryrun-email --verbose > 2.1.log 2>&1

./tracking-bugs-snapshot snap-stage2.1
./tracking-bugs-verify ref-tbs-stage2.1 snap-stage2.1
