#!/bin/sh

set -e
set +x

echo "  Stage 7:"
echo "    . Mark the regression-testing task as Fix Released."

# Set the promote-to-proposed task as completed on the various
# tracking bugs.
#
./tracking-bugs-modify mods-stage7

# The sru-workflow-manager should see that we are past the 1 hr
# grace perios and should set the next set of tasks to "Confirmed".
#
../swm --staging --dryrun-email --verbose > 7.log 2>&1

./tracking-bugs-snapshot snap-stage7
./tracking-bugs-verify ref-tbs-stage7 snap-stage7
