#!/usr/bin/python3
from __future__ import print_function

import os
import sys
import textwrap

sys.path.append(os.path.realpath(os.path.join(os.path.dirname(sys.argv[0]), '..', 'libs')))

from ktl.kernel_series import KernelSeries

def usage():
    print("""
Usage: bugs-config <mode>
       mode:
         packages <series> -- list of packages in series
          """.strip(), file=sys.stderr)
    sys.exit(1)

if len(sys.argv) < 2:
    usage()

mode = sys.argv[1]

kernel_series = KernelSeries()

if mode == 'packages':
    series_name = sys.argv[2]

    series = kernel_series.lookup_series(codename=series_name)
    for source in sorted(series.sources, key=lambda x: x.name):
        for package in source.packages:
            print(package.name)
