---
name: PR Pre Checks

on:
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize

env:
  KERNEL_SERIES_USE: local

jobs:
  multi-series-tests-ktl:
    strategy:
      matrix:
        image:
          - ubuntu-22.04
          - ubuntu-20.04
    runs-on: ${{ matrix.image }}
    steps:
      - step:
        name: Clone
        uses: actions/checkout@v4
        with:
          ref: ''
          repository: ''
          fetch-depth: 0
      - step:
        name: Show Versions
        run: |
          cat /etc/os-release
          python3 --version
          pip3 list
      - step:
        name: Run Tests
        run: |
          git config --global user.email "noreply+ckctreview-bot@canonical.com"
          git config --global user.name "Bot"
          pip3 install xdg
          pip3 install pytest
          pip3 install launchpadlib
          python3 -m pytest ktl

  multi-series-tests-remainder:
    strategy:
      matrix:
        image:
          - ubuntu-22.04
    runs-on: ${{ matrix.image }}
    steps:
      - step:
        name: Clone
        uses: actions/checkout@v4
        with:
          ref: ''
          repository: ''
          fetch-depth: 0
      - step:
        name: Show Versions
        run: |
          cat /etc/os-release
          python3 --version
          pip3 list
      - step:
        name: Run Tests
        run: |
          git config --global user.email "noreply+ckctreview-bot@canonical.com"
          git config --global user.name "Bot"
          pip3 install xdg
          pip3 install pytest
          # See Gitea Issue # 414
          python3 -m pytest --ignore ktl

  # Tests that are not affected by the host's environment
  series-agnostic-tests:
    runs-on: ubuntu-latest
    steps:
      - step:
        name: Clone
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      - step:
        name: Sign-off Check
        uses: actions/tnt-sign-off-check@v1
        with:
          check-owner-sob: false
      - name: Lint
        run: |
          pre-commit install
          pre-commit run --all-files
