---
name: PR Pre Checks

on:
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize

env:
  KERNEL_SERIES_USE: local

jobs:
  multi-series-tests:
    strategy:
      matrix:
        image:
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-18.04
    runs-on: ${{ matrix.image }}
    steps:
      - step:
        name: Clone
        uses: actions/checkout@v3
      - step:
        name: Show Versions
        run: |
          cat /etc/os-release
          python3 --version
          pip3 list
      - step:
        name: Run Tests
        run: |
          git config --global user.email "noreply+ckctreview-bot@canonical.com"
          git config --global user.name "Bot"
          pip3 install xdg
          (cd ktl/tests && python3 -m unittest -v)
          (cd cranky/crl/tests && python3 -m unittest -v)
          (cd cranky/annotations-tools && python3 -m unittest -v)

  # Tests that are not affected by the host's environment
  series-agnostic-tests:
    runs-on: ubuntu-latest
    steps:
      - step:
        name: Clone
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
      - step:
        name: Sign-off Check
        uses: actions/tnt-sign-off-check@v2
        with:
          check-owner-sob: false
      - name: Lint
        run: |
          pre-commit install
          pre-commit run --all-files
      - step:
        name: Run Tests
        run: |
          (cd info/tests && python3 -m unittest -v)
