---
name: PR Pre Checks

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

env:
  KERNEL_SERIES_USE: local

jobs:
  multi-series-tests:
    strategy:
      matrix:
        image:
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-18.04
    runs-on: ${{ matrix.image }}
    steps:
      - step:
        name: Clone
        uses: actions/checkout@v3
      - step:
        name: Show Versions
        run: |
          cat /etc/os-release
          python3 --version
          pip3 list
      - step:
        name: Run Tests
        run: |
          git config --global user.email "noreply+ckctreview-bot@canonical.co"
          git config --global user.name "Bot"
          (cd ktl/tests && python3 -m unittest -v)
          (cd cranky/crl/tests && python3 -m unittest -v)

  # Tests that are not affected by the host's environment
  series-agnostic-tests:
    runs-on: ubuntu-latest
    steps:
      - step:
        name: Clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Diff Bot
        uses: actions/tnt-diff-bot@v1
        with:
          syntax: symmetric
      - step:
        name: Sign-off Check
        uses: actions/tnt-sign-off-check@v1
        with:
          check-owner-sob: false
      - step:
        name: Run Tests
        run: |
          (cd info/tests && python3 -m unittest -v)
