---
name: PR Pre Checks

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  multi-series-tests:
    strategy:
      matrix:
        image:
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-18.04
    runs-on: ${{ matrix.image }}
    steps:
      - step:
        name: Clone
        uses: actions/checkout@v3
      - step:
        name: Show Versions
        run: |
          cat /etc/os-release
          python3 --version
          pip3 list
      - step:
        name: Run Tests
        run: |
          (cd ktl/tests && python3 -m unittest -v)

  # Tests that are not affected by the host's environment
  series-agnostic-tests:
    runs-on: ubuntu-latest
    steps:
        # Require branches to be namespaced to the user that generates the PR.
        # Multiple users may contribute to a branch as long as the branch name
        # is prefixed with the username of the PR owner.
      - name: Branch Namespace Check
        run: |
          branch_owner=${{ github.event.pull_request.user.username }}
          branch_name=${{ github.event.pull_request.head.ref }}
          re_namespace="^$branch_owner\/.+"
          if [[ ! $branch_name =~ $re_namespace ]]
          then
            echo "Your branch name is invalid. Please namespace your work."
            echo "Rename your branch $branch_owner/\$feature"
            exit 1
          else
            echo "Branch name '$branch_name' matches $re_namespace"
          fi
      - step:
        name: Clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - step:
        name: Sign-off Check
        uses: actions/tnt-sign-off-check@v1
      - step:
        name: Run Tests
        run: |
          (cd info/tests && python3 -m unittest -v)
