#!/usr/bin/env python3
#

from argparse                           import ArgumentParser, RawDescriptionHelpFormatter
from logging                            import basicConfig, DEBUG, WARNING
from ktl.ubuntu                         import Ubuntu

# Crankers
#
class Crankers():
    '''
    '''

    # __init__
    #
    def __init__(s, args):
        s.args = args

    # main
    #
    def main(s):
        retval = 1
        try:
            ubuntu = Ubuntu()
            for series in sorted(ubuntu.index_by_series_name, reverse=True):
                record = ubuntu.index_by_series_name[series]
                if record['supported']:
                    print(series)

                    print('    debs:')
                    for package in record['packages']:
                        print('        %s' % package)

                    if 'snaps' in record:
                        print('    snaps:')
                        for snap in record['snaps']:
                            print('        %s' % snap)

            retval = 0

        # Handle the user presses <ctrl-C>.
        #
        except KeyboardInterrupt:
            print("Aborting ...")

        if retval > 0:
            print("")
            print("Due to the above error(s), this script is unable to continue and is terminating.")
            print("")

        return retval

if __name__ == '__main__':
    app_description = '''
    '''

    app_epilog = '''
    '''

    parser = ArgumentParser(description=app_description, epilog=app_epilog, formatter_class=RawDescriptionHelpFormatter)
    parser.add_argument('--debug', action='store_true', default=False, help='Print out lots of stuff.')

    args = parser.parse_args()

    if args.debug:
        level = DEBUG
    else:
        level = WARNING
    basicConfig(filename=None, level=level, format="%(levelname)s - %(message)s")

    exit(Crankers(args).main())

# vi:set ts=4 sw=4 expandtab syntax=python:
