#!/usr/bin/env python3
#

from datetime                           import datetime, timedelta
from argparse                           import ArgumentParser, RawDescriptionHelpFormatter
from os                                 import path
from subprocess                         import Popen, PIPE
import re

# ErrorExit
#
class ErrorExit(Exception):
    def __init__(s, emsg):
        s.message = emsg

# TheApp
#
class TheApp(object):
    '''
    '''
    # sd
    #
    def sd(s, date):
        '''
        Starting date. Take the string passed in, verify it's a date we recognize and then pull it
        appart into the pieces that we need, returning a datetime object.
        '''
        date_rc = re.compile("^\d\d\d\d\.\d\d\.\d\d$")
        m = date_rc.match(date)
        if m is not None:
            t = datetime.strptime(date, '%Y.%m.%d')

            # Verify that the starting date is a friday.
            #
            if t.isoweekday() != 1:
                raise ErrorExit('The date specified must be the start date (Monday) of an SRU cycle.')
        else:
            raise ErrorExit('Badly formed date. Must be in YYYY.MM.DD format. For example: 2018.04.23')
        return t

    # print_cycle
    #
    def print_cycle(s, sd):
        sd = sd - timedelta(days=3)
        ed = sd + timedelta(days=22)

        print('')
        print('cycle: %s through %s' % (sd.strftime('%d-%b'), ed.strftime('%d-%b')))
        print('====================================================================')
        print('         %s   Last day for kernel commits for this cycle.' % (sd.strftime('%d-%b')))
        print('%s - %s   Kernel prep week.' %
                ((sd + timedelta(days=3)).strftime('%d-%b'), (sd + timedelta(days=8)).strftime('%d-%b')))
        print('%s - %s   Bug verification & Regression testing.' %
                ((sd + timedelta(days=9)).strftime('%d-%b'), (sd + timedelta(days=21)).strftime('%d-%b')))
        print('         %s   Release to -updates.' % ((sd + timedelta(days=24)).strftime('%d-%b')))
        print('')

    # main
    #
    def main(s, args):
        retval = 0

        sd = s.sd(args.date)
        print('To: Kernel SRU Announcements <kernel-sru-announce@lists.canonical.com>')
        print('Subject: A new SRU cycle started...')
        s.print_cycle(sd)

        print('')
        cmd = path.join(path.dirname(__file__), 'sru-cycle-kernel-versions')
        try:
            for line in Popen(cmd, shell=True, stdout=PIPE).stdout.readlines():
                print(line.rstrip().decode())
        except:
            raise ErrorExit('Failed calling %s for kernel versions.' % (cmd))

        print('')
        s.print_cycle(sd + timedelta(days=21))

        return retval

if __name__ == '__main__':
    retval = -1

    # Command line argument setup and initial processing
    #
    app_description = '''
    Generate the text for the email announcing the new SRU cycle dates amd kernel
    versions. The date which has to be given is the Monday which start the new cycle.
    '''
    app_epilog = '''
    '''
    parser = ArgumentParser(description=app_description, epilog=app_epilog, formatter_class=RawDescriptionHelpFormatter)
    parser.add_argument('date', metavar='<SRU cycle start date>', type=str, help='Date format: YYYY.MM.DD)')
    args = parser.parse_args()

    try:
        app = TheApp()
        retval = app.main(args)
    except ErrorExit as e:
        print('\n*** Error:')
        print('      %s\n' % e.message)

    exit(retval)

# vi:set ts=4 sw=4 expandtab syntax=python:
