#!/usr/bin/env python3
#

from argparse                           import ArgumentParser, RawTextHelpFormatter
from ktl.kernel_series                  import KernelSeries

if __name__ == '__main__':
    app_description = '''Print a list of all of the master kernel series that are supported
    '''
    app_epilog = '''
Examples:
    series
            This should give you a list of all of the supported series.
    '''

    parser = ArgumentParser(description=app_description, epilog=app_epilog, formatter_class=RawTextHelpFormatter)
    args = parser.parse_args()

    kernel_series = KernelSeries()

    for master_series in sorted(kernel_series.series, key=KernelSeries.key_series_name, reverse=True):
        if master_series.supported:
            print(master_series.codename)
