---
    board:
        lists:
          - 'Kernel Notice'
          - 'In Backlog'
          - 'To Do'
        default_list: 'In Backlog'
    cards:
        - name: 'Cycle Lead: <insert name>'
          description: 'Title needs to be updated with the name of the current lead. Lead to be assigned to the card.\n\nRole description and tasks: https://docs.google.com/document/d/1iI7NIsG6ymYtT7vNEets91SUfNgAvqenhjeh69JwRec/'
          list: 'Kernel Notice'
        - name: 'Cycle Status'
          description: 'Overall cycle status.'
          list: 'Kernel Notice'
        - name: 'Cycle README'
          description: '<Private information for crankers>\n\n{panel:bgColor=#e3fcef}\nPublic Information\n\n<Public information should go here>\n{panel}'
          list: 'Kernel Notice'
        - name: 'Re-spin (#1): Initial kernels'
          list: 'Kernel Notice'
        - name: 'Overall :prepare-packages progress'
          list: 'To Do'
        - name: 'Review automated-testing results'
          list: 'To Do'
        - name: 'Review regression-testing results'
          list: 'To Do'
        - name: 'Create tracking bugs'
          description: 'For each series for which kernels should be cranked, run "create-kernel-tasks --series <series> --spin 1 <cycle date>".'
          list: 'To Do'
        - name: 'Apply patches from the ML'
          list: 'To Do'
