#!/usr/bin/env python3
#

from argparse                           import ArgumentParser, RawDescriptionHelpFormatter
from ktl.kernel_series                  import KernelSeries
import json
import yaml

# Crankers
#
class Crankers():
    '''
    '''

    # __init__
    #
    def __init__(s, args):
        s.args = args

    # main
    #
    def main(s):
        retval = 1
        try:
            data = {}
            kernel_series = KernelSeries()
            for series in sorted(kernel_series.series, key=KernelSeries.key_series_name, reverse=True):
                if not series.supported:
                    continue

                data[series.codename] = {}
                data[series.codename]['debs'] = []
                for source in series.sources:
                    if not source.supported or source.copy_forward:
                        continue
                    for package in source.packages:
                        data[series.codename]['debs'].append(package.name)

            if s.args.yaml:
                print(yaml.dump(data, default_flow_style=False, indent=4, explicit_start=True))

            elif s.args.json:
                print(json.dumps(data, sort_keys=True, indent=4))

            else:
                for series in sorted(data):
                    print(series)
                    print('    debs:')
                    for deb in sorted(data[series]['debs']):
                        print('        ' + deb)

            retval = 0

        # Handle the user presses <ctrl-C>.
        #
        except KeyboardInterrupt:
            print("Aborting ...")

        if retval > 0:
            print("")
            print("Due to the above error(s), this script is unable to continue and is terminating.")
            print("")

        return retval

if __name__ == '__main__':
    app_description = '''
    '''

    app_epilog = '''
    '''

    parser = ArgumentParser(description=app_description, epilog=app_epilog, formatter_class=RawDescriptionHelpFormatter)
    parser.add_argument('--yaml', action='store_true', default=False, help='Dump it out in yaml format')
    parser.add_argument('--json', action='store_true', default=False, help='Dump it out in json format')

    args = parser.parse_args()

    exit(Crankers(args).main())

# vi:set ts=4 sw=4 expandtab syntax=python:
