#!/bin/bash

here=$(dirname "$(readlink -f "${0}")")

# We are meant to run in the swm directory.
cd "$here" || exit 1

export http_proxy="http://squid.internal:3128"
export https_proxy="https://squid.internal:3128"
export no_proxy="launchpad.net,.launchpad.net,kernel.ubuntu.com"

set -o pipefail
"$here/swm-jira-sync" "$@" 2>&1 | tee -a "$HOME/logs/swm-jira-sync.log"
