#!/bin/bash

if [ "$#" -lt 4 -o "$#" -gt 5 ]; then
	echo "Usage: $0 <name> <title> <warn> <alert> [<note>]" 1>&2
	exit 1
fi
name="$1"
title="$2"
warn="$3"
alert="$4"
note="$5"

# Fix the description.
title=`echo "$title" | sed -e 's/%/%p/g' -e 's/ /%s/g'`

# Make a simple update.
echo "$title `date +%s` $warn $alert $note" | "$0-bulk" "$name"
