#!/bin/bash

# We must have a name, otherwise handle the arguments as below.
if [ "$#" -lt 2 ]; then
	echo "Usage: $0 <name> <group> <title> <warn> <alert> [<note>]" 1>&2
	echo "Usage: $0 <name> [<group>] [<title>] [<warn>] [<alert>] [<note>] [<key=value>]..." 1>&2
	exit 1
fi

declare -a keys

# Pick off the default positions.
name="$1"
shift
for fixed in group title warning alert note
do
	case "$1" in
	*=*|'')		break ;;
	esac
	# Encode things that need it.
	value=`echo "$1" | sed -e 's/%/%p/g' -e 's/ /%s/g'`
	keys[${#keys[*]}]="$fixed=$value"
	shift
done

host=0
stamp=0
for arg in "$@"
do
	case "$arg" in
	*=*)		;;
	host=*)		host=1 ;;
	stamp=*)	stamp=1 ;;
	*)	echo "$arg: invalid after key=value pair" 1>&2
		exit 1
		;;
	esac
	# Encode things that need it.
	value=`echo "$arg" | sed -e 's/%/%p/g' -e 's/ /%s/g'`
	keys[${#keys[*]}]="$value"
	shift
done

# Fill in required and defaulted values.
[ "$host" -eq 0 ] && keys[${#keys[*]}]="host=`uname -n`"
[ "$stamp" -eq 0 ] && keys[${#keys[*]}]="stamp=`date +%s`"

echo "V2 ${keys[*]}" | "$0-bulk" "$name"
