#!/bin/bash

out="$HOME/public_html/status"
state="$out/dashboard-state"

mkdir -p "$state"

now=`date +%s`
date=`date '+%d-%b-%Y %H:%M'`

let later="$now+100"

{
	echo "dashboard Dashboard `hostname` Scheduled%sUpdate $now $later $later"
	while read file title host url
	do
		# Get this if we can ... ignore it, we will use the previous data.
		wget -q -O "$state/$file.new" "$url" && mv "$state/$file.new" "$state/$file"

		if [ -f "$state/$file" ]; then
			while read -r line
			do
				echo "$file $title $host $line"
			done <"$state/$file"
		else
			echo "$file $title $host MISSING%sDASHBOARD $now -1 -1"
		fi
	done <<EOL
people-dkms-matrix DKMS%sMatrix people http://people.canonical.com/~kernel/status/dkms.dashboard
people-cve-autotriage CVE%sAutotriage people http://people.canonical.com/~kernel/status/cve-autotriage.dashboard
people-cve-matrix CVE%sAutotriage people http://people.canonical.com/~kernel/status/cve-matrix.dashboard
zinc-mainline-daily Mainline%sBuilds zinc http://zinc.canonical.com/~kernel-ppa/status/mainline-daily.dashboard
zinc-mainline-hourly Mainline%sBuilds zinc http://zinc.canonical.com/~kernel-ppa/status/mainline-hourly.dashboard
zinc-mainline-cleanup Mainline%sBuilds zinc http://zinc.canonical.com/~kernel-ppa/status/mainline-cleanup.dashboard
zinc-mainline-cod-incoming-publish Mainline%sBuilds zinc http://zinc.canonical.com/~kernel-ppa/status/mainline-cod-incoming-publish.dashboard
gomeisa-mainline-queue Mainline%sBuilds gomeisa http://zinc.canonical.com/~kernel-ppa/status/gomeisa-mainline-queue.dashboard
tangerine-mainline-queue Mainline%sBuilds tangerine http://zinc.canonical.com/~kernel-ppa/status/tangerine-mainline-queue.dashboard
people-update-tools Maintenance people http://people.canonical.com/~kernel/status/update-tools.dashboard
people-update-lptk Maintenance people http://people.canonical.com/~kernel/status/update-lptk.dashboard
zinc-update-repos Maintenance zinc http://zinc.canonical.com/~kernel-ppa/status/zinc-update-repos.dashboard
gomeisa-update-repos Maintenance gomeisa http://zinc.canonical.com/~kernel-ppa/status/gomeisa-update-repos.dashboard
zinc-shankbot-swm ShankBot zinc http://zinc.canonical.com/~kernel-ppa/status/shankbot-swm.dashboard
zinc-proposed-watcher Proposed%sMigration zinc http://zinc.canonical.com/~kernel-ppa/status/proposed-watcher.dashboard
EOL
} | {

	status="$out/dashboard"

	: >"$status.txt.new"
	cat - <<EOL >"$status.html.new"
<html>
<head>
<meta http-equiv="refresh" content="60">
<title>Kernel Dashboard</title>
<style>
.good { background-color: green; }
.warn { background-color: yellow; }
.alert { background-color: red; }
table.status {
    border-collapse: collapse;
}
table.status, table.status th, table.status td {
   border: 1px solid black;
} 
</style>
<script>
function pageLoaded() {
	if (!Date.now) {
	    Date.now = function() { return new Date().getTime(); }
	}
	now = Math.floor(Date.now() / 1000)
	if ((now - $now) > (300 + 60 + 30)) {
		document.getElementById("dashboard").style.background = "red";
	}
}
</script>
</head>
<body onload="pageLoaded()">
<h1>Kernel Dashboard ($date)</h1>
<table width=60% class="status">
<tr><th colspan=3>Tool<th>Last<th>Notes</tr>
EOL
	#last_title=''
	while read section title host tag time warning alert message
	do
		let delta="$now-$time"
		if [ "$delta" -gt "$alert" ]; then
			mode="alert"
		elif [ "$delta" -gt "$warning" ]; then
			mode="warn"
		else
			mode="good"
		fi
		echo "$section $tag $time $warning $alert"
		echo "$title $tag $host $delta $mode" >>"$status.txt.new"

		title=`echo "$title" | sed -e 's/%s/ /g' -e 's/%p/%/g'`
		tag=`echo "$tag" | sed -e 's/%s/ /g' -e 's/%p/%/g'`
		
		#if [ "$last_title" = "$title" ]; then
		#	title="&nbsp;"
		#else
		#	last_title="$title"
		#fi

		# Ensure we do not execute something other than a number.
		#let time="$time + 0"
		#time=`date --date=@$time '+%d-%b-%Y %H:%M'`

		let delta="$delta / 60"
		ext='m'
		if [ "$delta" -ge 60 ]; then
			let delta="$delta / 60"
			ext='h'

			if [ "$delta" -ge "24" ]; then
				let delta="$delta / 24"
				ext='d'
			fi
		fi
		echo "<tr id=\"$section\" class=\"$mode\"><td>$title<td>$tag<td>$host<td>$delta$ext<td>$message</tr>" >>"$status.html.new"
	done

	cat - <<EOL >>"$status.html.new"
</table>
</body>
</html>
EOL

	mv -f "$status.html.new" "$status.html"
	mv -f "$status.txt.new" "$status.txt"
}
