#!/bin/bash

if [ "$#" -ne 1 -a "$#" -ne 2 ]; then
	echo "Usage: $0 <name> [<host>]" 1>&2
	exit 1
fi
name="$1"
host="$2"
[ "$#" -lt 2 ] && host=`uname -n`

# If this is a filename then use it as is, else use the default location, adding the
# host if not specified.
case "$name" in
*/*)		;;
$host-*)	;;
*)		name="$host-$name" ;;
esac

case "$name" in
*/*)	;;
*)
	mkdir -p "$HOME/public_html/status/dashboard-status"
	name="$HOME/public_html/status/dashboard-status/$name.dash"
	;;
esac

while read group host title stamp warn alert note
do
	# Handle basic multipliers.
	case "$warn" in
	*m)	let warn="${warn%m}*60" ;;
	*h)	let warn="${warn%h}*3600" ;;
	esac
	case "$alert" in
	*m)	let alert="${alert%m}*60" ;;
	*h)	let alert="${alert%h}*3600" ;;
	esac

	echo "$group $host $title $stamp $warn $alert $note"
done >"$name.new"

# All done install it.
mv -f "$name.new" "$name"
