#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

out="$HOME/public_html/status/dashboard-helper/proposed-migration"
mkdir -p "$out"

timestamp()
{
	local url="$1"

	RET=`wget -q --server-response --spider "$url" 2>&1 | awk '/Last-Modified:/ { $1=""; print }'`
	RET=`date --date="$RET" +%s`
}

"$here/dashboard-config" britney | \
{
	while read name url pockets
	do
		file="$out/$name"
		outd="$out/$name"
		mkdir -p "$outd"

		# Get the file update_excuses.yaml iff it has changed.
		urlt="$url/update_excuses.yaml.xz"
		fname_xz=`basename "$urlt"`
		fname=`basename "$urlt" .xz`
		(cd "$outd" && wget -qN -nd "$urlt")
		if [ -f "$outd/$fname_xz" ]; then
			xz --decompress <"$outd/$fname_xz" >"$outd/$fname.live"
			ln -f "$outd/$fname.live" "$file.migration"
		fi

		# Look at the triggers for a base timestamp.
		stamp=0
		for pocket in $pockets
		do
			purl="http://ftpmaster.internal/ubuntu/dists/$pocket/Release"
			timestamp "$purl"
			[ "$RET" -gt "$stamp" ] && stamp="$RET"
		done

		echo "$name $file.migration $stamp"
	done
} | "$here/helper-proposed-migration-payload" "$out/regressions.txt.new" "$out/overall.txt.new" | \
    "$here/dashboard/dashboard-status-bulk" "proposed-watcher"

mv -f "$out/regressions.txt.new" "$out/regressions.txt"
mv -f "$out/overall.txt.new" "$out/overall.txt"
