#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

out="$HOME/public_html/status/dashboard-helper/proposed-migration"
mkdir -p "$out"

timestamp()
{
	local url="$1"

	RET=`wget -q --server-response --spider "$url" 2>&1 | awk '/Last-Modified:/ { $1=""; print }'`
	RET=`date --date="$RET" +%s`
}

{
	while read name url pockets
	do
		file="$out/$name.migration"
		outd="$out/$name"
		mkdir -p "$outd"

		# Get the file iff it has changed.
		fname=`basename "$url"`
		(cd "$outd" && wget -qN -nd "$url")
		if [ -f "$outd/$fname" ]; then
			ln -f "$outd/$fname" "$file"
		fi

		# Look at the triggers for a base timestamp.
		stamp=0
		for turl in $pockets
		do
			timestamp "$turl"
			[ "$RET" -gt "$stamp" ] && stamp="$RET"
		done

		echo "$file $stamp"
	done <<EOL
devel http://people.canonical.com/~ubuntu-archive/proposed-migration/update_excuses.yaml http://archive.ubuntu.com/ubuntu/dists/vivid/Release http://archive.ubuntu.com/ubuntu/dists/vivid-proposed/Release
trusty http://people.canonical.com/~ubuntu-archive/proposed-migration/trusty/update_excuses.yaml http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release http://archive.ubuntu.com/ubuntu/dists/trusty-proposed/Release
utopic http://people.canonical.com/~ubuntu-archive/proposed-migration/utopic/update_excuses.yaml http://archive.ubuntu.com/ubuntu/dists/utopic-updates/Release http://archive.ubuntu.com/ubuntu/dists/trusty-proposed/Release
EOL
} | "$here/helper-proposed-migration-payload" | \
    "$here/dashboard-status-bulk" "proposed-watcher"
