#!/usr/bin/env python
#
from __future__ import print_function

import os
from argparse                           import ArgumentParser, RawDescriptionHelpFormatter
from logging                            import basicConfig, DEBUG, WARNING
import socket
import threading
import Queue
from ktl.log                            import cdebug, center, cleave, cerror
import ssl
from ktl.msgq                           import MsgQueue
import json

# TheApp
#
class TheApp():
    '''
    This class is just the engine that makes everything go.
    '''

    # __init__
    #
    def __init__(s, args):
        '''
        '''
        s.args = args

        s.db_name = os.path.join(s.args.statedir, 'state.json')
        s.db_data = {}

        if os.path.exists(s.db_name):
            with file(s.db_name) as dbf:
                s.db_data = json.load(dbf)

    # _db_write
    #
    def _db_write(s):
        # Sync the database back.
        with open(s.db_name + '.new', 'w') as dbf:
            json.dump(s.db_data, dbf, indent=4)
        os.rename(s.db_name + '.new', s.db_name)

        cdebug("status database written")
        
    # _handler_status_bulk
    #
    def _handler_status_bulk(s, payload):
        cdebug("TheApp::_handler_status_bulk")
        # Validate the incoming record.
        for field in ('id', 'rhost'):
            if field not in payload:
                cerror("status-bulk: missing {0}, ignored".format(field))
                return
        if '/' in payload['id']:
            cerror("status-bulk: bad id <{0}>, ignored".format(uid))
            return

        cdebug("bulk update seems valid")

        # If the id does not include the rhost, add it.
        if not payload['id'].startswith(payload['rhost'] + '-'):
            payload['id'] = payload['rhost'] + '-' + payload['id']
        uid = payload['id']

        # Fill in any missing information in the updates.
        if 'updates' in payload:
            for update in payload['updates']:
                if 'order' not in update:
                    update['order'] = 50
                if 'group_order' not in update:
                    if update['group'] == 'Dashboard':
                        update['gorder'] = 0
                    elif update['group'].startswith('Host:'):
                        update['gorder'] = 90
                    else:
                        update['gorder'] = 50

        # Install the new record.
        if 'updates' in payload:
            s.db_data[uid] = payload['updates']
        else:
            del s.db_data[uid]
        s._db_write()

        # Write out this bulk batch into a file by uid.
        sfilen = os.path.join(s.args.statedir, uid + ".new")
        sfile  = os.path.join(s.args.statedir, uid + ".dash")

        if 'updates' in payload:
            with open(sfilen, "w") as sfd:
                for update in payload['updates']:
                    line = 'V2 rhost=' + payload['rhost'].replace('%', '%p').replace(' ', '%s')
                    for key in update.keys():
                        line += ' ' + key + '=' + str(update[key]).replace('%', '%p').replace(' ', '%s')
                    print(line, file=sfd)

            os.rename(sfilen, sfile)
        else:
            os.unlink(sfile)

        cdebug("bulk update written")

    # _handler
    #
    def _handler(s, payload):
        cdebug("TheApp::_handler")

        if payload['key'] == 'kernel.dashboard.status.bulk':
            s._handler_status_bulk(payload)
        else:
            cerror("Unknown op <{0}>, ignored".format(payload['op']))

    # main
    #
    def main(s):
        '''
        '''
        retval = 1

        try:
            if args.local:
                mq = MsgQueue(address='localhost', port=9123)
            else:
                mq = MsgQueue()
            mq.listen(s.args.queue, 'kernel.dashboard.status.bulk', s._handler)

            print("done")
            retval = 0
        # Handle the user presses <ctrl-C>.
        #
        except KeyboardInterrupt:
            print("Aborting ...")

        return retval

if __name__ == '__main__':
    # Command line argument setup and initial processing
    #
    app_description = '''
I'm a application skeleton, your job is to make me into something useful.
    '''
    app_epilog = '''
examples:
    KernelMQ --help
    '''
    parser = ArgumentParser(description=app_description, epilog=app_epilog, formatter_class=RawDescriptionHelpFormatter)
    parser.add_argument('--debug', action='store_true', default=False, help='Print out a lot of messages about what is going on.')
    parser.add_argument('--local', action='store_true', default=False, help='Assume we have sshuttle setup to the MQ server.')
    parser.add_argument('queue', help='Name of the queue to use')
    parser.add_argument('statedir', help='Name of the output state dir')
    args = parser.parse_args()

    # If logging parameters were set on the command line, handle them
    # here.
    #
    log_format = "%(levelname)s - %(message)s"
    if args.debug:
        basicConfig(level=DEBUG, format=log_format)
    else:
        basicConfig(level=WARNING, format=log_format)

    app = TheApp(args)
    exit(app.main())


# vi:set ts=4 sw=4 expandtab:

