#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <repo>" 1>&2
	exit 1
fi

base="$1"
. "$base/debian/debian.env"
for config in "$base/CONFIGS"/*
do
	name=`basename "$config"`
	echo "$name" | sed -e 's/-config\.flavour\./ /g' | {
		read arch flavour
		if [ ! -f "$base/$DEBIAN/config/$arch/config.flavour.$flavour" ]; then
			continue
		fi
		echo "*** $arch $flavour ..."
		"$here//devel-config-apply" "$base" "$base/debian.master/config/annotations" "$arch" "$flavour" "$base/CONFIGS/$arch-config.flavour.$flavour" >>"$base/$DEBIAN/config/$arch/config.flavour.$flavour"
	}
done
