#! /bin/bash 
#
# devel-config-info -- generate the configuration info tables.
#
P="$0"

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

annotations="$1"
base="$2"

archs=`grep 'ARCH:' "$annotations" | cut -c 9-`
if [ "$archs" = '' ]; then
	archs='x86 arm powerpc'
fi

# Generate per architecture configuration trees
rm -f "$base/CONFIGS-parser-"* "$base/CONFIGS-info-"*
for arch in $archs
do
	"$here/devel-config-parser" "$base" arch/$arch/Kconfig "$base/CONFIGS-parser-$arch"
	"$here/devel-config-tree" "$base/CONFIGS-parser-$arch" geninfo >"$base/CONFIGS-info-$arch"
done

# Generate the config renames.
{
	for arch in $archs
	do
		"$here/devel-config-tree" "$base/CONFIGS-parser-$arch" genrenames
	done
} | tee APW-renames | "$here/devel-config-calc-renames" >"$base/CONFIGS-renames"

# Generate the expanded annotations.
{
	for arch in $archs
	do
		"$here/devel-config-tree" "$base/CONFIGS-parser-$arch" expand "$base/CONFIGS-renames" <"$annotations"
	done
} | tee APW-premerge | "$here/devel-arch-annotations-merge" >"$base/CONFIGS-annotations"

# Generate a common merged configuration version.
"$here/devel-arch-info-merge" "$base/CONFIGS-info" "$base/CONFIGS-annotations" "$base/CONFIGS-info-"*

# Legacy formats.
awk '{ print $1 " " $2 " " $3 }' <"$base/CONFIGS-info" >"$base/CONFIGS-defaults"
