#! /bin/bash 
#
# devel-config-info -- generate the configuration info tables.
#
P="$0"

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

annotations="$1"
base="$2"

archs=`grep 'ARCH:' "$annotations" | cut -c 9-`
if [ "$archs" = '' ]; then
	archs='x86 arm powerpc'
fi

# Generate per architecture configuration trees
rm -f "$base/CONFIGS-parser-"*
for arch in $archs
do
	"$here/devel-config-parser" "$base" arch/$arch/Kconfig "$base/CONFIGS-parser-$arch"
done

{
	for arch in $archs
	do
		"$here/devel-config-tree" "$base/CONFIGS-parser-$arch" genrenames
	done
} | tee "$base/CONFIGS-debug-renames" | "$here/devel-config-calc-renames" >"$base/CONFIGS-renames"

{
	for arch in $archs
	do
		"$here/devel-config-tree" "$base/CONFIGS-parser-$arch" genorder "$base/CONFIGS-renames"
	done
} | tee "$base/CONFIGS-debug-menus" | LANG=C sort -k 2 | "$here/devel-menu-sanitise" >"$base/CONFIGS-menu-order"

{
	for arch in $archs
	do
		"$here/devel-config-tree" "$base/CONFIGS-parser-$arch" annotations "$base/CONFIGS-renames"
	done
} | tee "$base/CONFIGS-debug-flags" | LANG=C sort | uniq >"$base/CONFIGS-annotation-flags"
