#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

base="$HOME/git2/ubuntu-nexus7"
. "$base/debian/debian.env"
for config in "$base/CONFIGS"/*
do
	name=`basename "$config"`
	echo "$name" | sed -e 's/-config\.flavour\./ /g' | {
		read arch flavour
		if [ ! -f "$base/$DEBIAN/config/$arch/config.flavour.$flavour" ]; then
			continue
		fi
		echo "*** $arch $flavour ..."
		"$here//devel-config-apply" "$base" "$base/debian.master/config/annotations" "$arch" "$flavour" "$base/CONFIGS/$arch-config.flavour.$flavour" >>"$base/$DEBIAN/config/$arch/config.flavour.$flavour"
	}
done
