#! /bin/bash
#
# devel-config-apply -- generate a list of configuration options to attempt to apply
#
P="$0"

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

base="$1"
annotations="$2"
arch="$3"
flavour="$4"
config="$5"

case "$arch" in
i386|amd64)		karch='x86' ;;
armel|armhf|arm64)	karch='arm' ;;
powerpc|ppc64el)	karch='powerpc' ;;
s390x)			karch='s390' ;;
*)			echo "$arch: architecture unknown" 1>&2; exit 1 ;;
esac

# Generate the expanded annotations.
cat "$annotations" | tee APW3 | \
	"$here/devel-config-tree" "$base/CONFIGS-parser-$karch" expand "$base/CONFIGS-renames" | tee APW1 | \
	"$here/devel-arch-annotations-merge" | tee APW2 | \
	"$here/devel-config-apply-payload" "$arch" "$flavour" "$config"
