#!/usr/bin/env python3
#
# Checkout the trees that make up a set of kernel packages
#

import argparse
import logging
import os
import sys

from crl.git import GitHandleSet, GitError
from crl.config import Config
from crl.handle import HandleError
from ktl.log import cerror, cnotice


def checkout_repos(handle, reference=None, dissociate=False):
    """
    Clone the repos that make up the set of kernel packages
    """
    # Cycle through the trees and clone/update the package specific
    # repositories.
    ghs = GitHandleSet(handle)

    cnotice("Codename: {}".format(ghs.codename))
    cnotice("Source:   {}".format(ghs.source.name))

    summary = []
    for gh in ghs:
        repo_dir = gh.directory

        # Make the parental directories.
        if not os.path.exists(os.path.dirname(repo_dir)):
            os.makedirs(os.path.dirname(repo_dir))

        # Update an existing repo or otherwise clone it
        if os.path.exists(os.path.join(repo_dir, '.git')):
            gh.update_remote(gh.remote, gh.get_url())
        else:
            gh.clone(reference, dissociate)

        # Configure the git repo. Do this every time in case things have
        # changed, for example when a release transitions to ESM.
        gh.configure()

    for gh in ghs:
        pkg        = gh.package
        remote     = gh.remote
        rmt_branch = gh.remote_branch
        branch     = gh.get_cranky_branch_name()

        # Add info for the summary
        summary.append({"name": pkg.name, "dir": gh.directory, "remote": remote,
                        "branch": branch})

        gh.checkout(remote, rmt_branch, branch)

    # Print the summary
    cnotice("Summary:")
    for s in summary:
        cnotice("  Repo '{}' in directory '{}' (branch '{}')".format(
                s["name"], s["dir"], s["branch"]))


def expanduser(path):
    if path:
        path = os.path.expanduser(path)
    return path


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    # Get the config options from file
    config = Config()
    if config.lookup('clone', None) is not None:
        cerror("Deprecated 'clone' section found in the .cranky config file.")
        cerror("You need to remove it or rename it to 'checkout'.")
        sys.exit(1)
    config_cmd = config.lookup('checkout', {})

    desc = """
Checkout the repos (typically 'linux', 'linux-meta', and 'linux-signed') that
make up a set of Ubuntu kernel packages. The repos are cloned first, if they
don't yet exist locally. The local directories where the repos are cloned into
are specified in the cranky config file (see 'package-path' in the
'Configuration file' section below).
"""

    epilog = """
Examples:
  $ cranky checkout xenial:linux
      Checkout the 'linux', 'linux-meta' and 'linux-signed' repositories for
      Xenial.

  $ cranky checkout --reference /home/work/linux-2.6 xenial:linux
      Same as above but use a local clone of Linus' upstream repo as a git
      reference.

  $ cranky checkout xenial:linux-aws
      Checkout the 'linux-aws', 'linux-meta-aws' and 'linux-signed-aws'
      repositories for the Xenial AWS variant.

  $ cranky checkout xenial:linux-raspi2
      This variant doesn't have stand-alone repos but instead resides on
      branches of the main 'linux', 'linux-meta' and 'linux-signed' repos. See
      below for more details.

Notes:
  Some kernel variants have their own repos (like aws, for example) whereas
  others simply reside on branches of the main repos (like raspi2). Depending
  on the 'package-path' configuration in your .cranky config file you'll end
  up with one local clone per repo or with individual clones for the different
  variants which means you'll have multiple local copies of the same repo.

Configuration file:
  ~/.cranky is a yaml format configuration file where the optional commandline
  options can be specified. Note that options specified via the commandline
  take precedence over options from the configuration file.

  Example ~/.cranky section:
  ---
    checkout:
      reference: '/home/repo/linux-2.6'
      dissociate: true
    package-path:
      default: ~/git/ubuntu/{series}/{package}
"""

    help_handle = """
Handle to a kernel source tree in <series>:<package> format.
"""

    help_reference = """
Obtain objects from an existing local repository to speed up the cloning
process. This is a git clone option, check 'git help clone' for more details.
Note that without using --dissociate, the referenced repo *must not* be deleted
otherwise the cranky checkout'd repo will get corrupted.
"""

    help_dissociate = """
Borrow the objects from the referenced local repository only to reduce network
traffic. This is a git clone option, check 'git help clone' for more details.
"""

    formatter = argparse.RawDescriptionHelpFormatter
    parser = argparse.ArgumentParser(description=desc,
                                     formatter_class=formatter,
                                     epilog=epilog,
                                     prog="cranky checkout")
    parser.add_argument("handle", help=help_handle)
    parser.add_argument("-r", "--reference",
                        default=expanduser(config_cmd.get('reference', None)),
                        help=help_reference)
    parser.add_argument("-d", "--dissociate", action="store_true",
                        default=config_cmd.get('dissociate', False),
                        help=help_dissociate)

    try:
        checkout_repos(**vars(parser.parse_args()))
    except (HandleError, GitError) as e:
        cerror(e)
        sys.exit(1)
