#!/bin/bash -eu

# TODO:
#  - error handling
#  - parameters
#  - config for mapping 'bionic/main' -> git2/ubuntu-bionic
#  - -v needs to be something ... sometimes
#  - -sa too
#  - unstable is not the series
#  - --meta-option v=<sometihg>
#  - --profile <override> in concert with series-linux as "overrides"

# Support arm64 and amd64 as chroot arches, everyone else gets to use amd64 with qemu-user-static
if [ "$(dpkg --print-architecture)" = "arm64" ]; then
	chroot_arch="arm64"
	x86_compiler="gcc-x86-64-linux-gnu"
	x86_libc="libc6-dev-amd64-cross"
	arm64_compiler="gcc"
	arm64_libc="libc6-dev"
else
	chroot_arch="amd64"
	x86_compiler="gcc"
	x86_libc="libc6-dev"
	arm64_compiler="gcc-aarch64-linux-gnu"
	arm64_libc="libc6-dev-arm64-cross"
fi

function out()
{
	local rc=$?

	trap - INT TERM EXIT HUP

	if [ ${rc} -ne 0 ] ; then
		if [ -n "${OUT_SESSION}" ] ; then
			# create-session failed so kill the broken session
			schroot -e -c "${OUT_SESSION}"
		fi
		echo "Script failed" >&2
	fi

	exit "${rc}"
}

base_chroot_available()
{
	local series="$1"
	local arch="$2"

	local chroot

	for chroot in "$series-security-$arch-sbuild" "$series-$arch-sbuild" "$series-$arch"
	do
		schroot --directory / -c "$chroot" /bin/true >/dev/null 2>&1 && {
			#echo "II: $chroot base chroot available"
			RET="$chroot"
			return 0
		}
	done
	RET=""
	return 1
}

base_chroot_create()
{
	local series="$1"
	local arch="$2"

	local chroot="$series-$arch"

	# Create the base chroot.
	echo "$P: $chroot base chroot needed -- creating" 1>&2

	if ! grep -s '^/home' '/etc/schroot/sbuild/fstab' >/dev/null; then
		cat - <<'EOF' | sudo tee --append '/etc/schroot/sbuild/fstab' >/dev/null
# Allow use of /home for use with cranky.
/home           /home           none    rw,bind         0       0
EOF
	fi
	mk-sbuild --skip-updates --skip-proposed --distro="ubuntu" --arch="$arch" "$series"

	RET="$chroot"
}

session_chroot_available()
{
	local series="$1"
	local arch="$2"
	local package="$3"
	local which="$4"

	local session="session:cranky-$series-$arch-$which"

	# Validate the session.
	schroot --directory / -r -c "$session" /bin/true >/dev/null 2>&1 && {
		#echo "II: $session session available"
		RET="$session"
		return 0
	}
	RET=""
	return 1
}

session_chroot_create()
{
	local series="$1"
	local arch="$2"
	local package="$3"
	local which="$4"

	local session="cranky-$series-$arch-$which"

	if ! base_chroot_available "$series" "$arch"; then
		echo "$P: base chroot not available -- run: $C chroot create-base \"$series:linux\""
		return 1
	fi
	local chroot="$RET"

	# Create the base session.
	echo "$P: $session session needed -- creating" 1>&2

	schroot -b -n "$session" -c "$chroot"
	session="session:$session"
	OUT_SESSION=${session}   # Used by the exit handler

	if [ "${series}" != "trusty" ] && [ "${series}" != "xenial" ]; then
		# Add the builder-extra PPA to keep the chroots consistent with
		# the packages used during the sources build.
		# The PPA used for ESM kernels currently doesn't have any extra
		# dependency, so exclude trusty and xenial.
		repo_pub_key=$(cat $(dirname "$C")/cmds.d/builder-extra.asc)
		schroot -u root -r -c "$session" -- sh -c "echo '${repo_pub_key}' > /etc/apt/trusted.gpg.d/builder-extra.asc"
		schroot -u root -r -c "$session" -- sh -c "echo 'deb http://ppa.launchpad.net/canonical-kernel-team/builder-extra/ubuntu ${series} main' > /etc/apt/sources.list.d/builder-extra.list"
	fi

	schroot -u root -r -c "$session" -- apt-get update
	schroot -u root -r -c "$session" -- apt-get -y dist-upgrade

	schroot -u root -r -c "$session" -- apt-get -y -o APT::Get::Only-Source=true build-dep --no-install-recommends "$package"

	# XXX: session specific in it ...

	RET="$session"

	# The kernels supported on Trusty don't need cross-compilers so don't
	# install them
	if [ "${series}" = "trusty" ] ; then
		return
	fi

	# Cross Compilers
	schroot -u root -r -c "$session" -- apt-get -y -o APT::Get::Only-Source=true install $arm64_compiler gcc-arm-linux-gnueabihf gcc-powerpc64le-linux-gnu gcc-s390x-linux-gnu $x86_compiler

	# Allow CC to link to libc
	schroot -u root -r -c "$session" -- apt-get -y -o APT::Get::Only-Source=true install $arm64_libc libc6-dev-armhf-cross libc6-dev-ppc64el-cross libc6-dev-s390x-cross $x86_libc

	if [ "${series}" != "xenial" ] ; then
		# Xenial doesn't have these packages
		schroot -u root -r -c "$session" -- apt-get -y -o APT::Get::Only-Source=true install gcc-i686-linux-gnu libc6-dev-i386-cross gcc-riscv64-linux-gnu libc6-dev-riscv64-cross
	fi

	# Fixups to support backport kernels
	if [ "${series}" = "jammy" ] ; then
		# Compiling Kinetic kernels requires gcc-12
		schroot -u root -r -c "$session" -- apt-get -y -o APT::Get::Only-Source=true install ${arm64_compiler/gcc/gcc-12} gcc-12-arm-linux-gnueabihf gcc-12-powerpc64le-linux-gnu gcc-12-s390x-linux-gnu gcc-12-riscv64-linux-gnu  ${x86_compiler/gcc/gcc-12}
	fi
	if [ "${series}" = "focal" ] ; then
		# Compiling Hirsute and later kernels requires dctrl-tools
		schroot -u root -r -c "$session" -- apt-get -y -o APT::Get::Only-Source=true install dctrl-tools

		# riscv kernels need gcc-10
		schroot -u root -r -c "$session" -- apt-get -y -o APT::Get::Only-Source=true install gcc-10-riscv64-linux-gnu
	fi

	if [ "${series}" = "bionic" ] ; then
		# Compiling Focal and later kernels requires dwarves
		schroot -u root -r -c "$session" -- apt-get -y -o APT::Get::Only-Source=true install dwarves
	fi
}

chroot_update() {
	local chroot="$1"

	local open
	case "$chroot" in
	session:*)	open="-r -c" ;;
	*)		open="-c" ;;
	esac

	schroot -u root $open "$chroot" -- apt-get update
	schroot -u root $open "$chroot" -- apt-get -y dist-upgrade
}

usage()
{
	cat <<EOF
Usage: cranky chroot <commands> <args>...
commands:
  create-base [<handle>]
      Create a base sbuilder chroot for the series of the handle package.
  create-session configs|sources [<handle>]
      Create a session for the requested purpose.
  map-session configs|sources [<handle>]
      Emit the name of the required session if available.
  run [<handle>] -- command
      Run command under chroot.
  destroy-session configs|sources [<handle>]
      Destroy the session created for the specified purpose.

Build either base chroots or chroot sessions appropriate for building
sources or updating configurations.

positional arguments:
  handle
      Handle to a kernel source tree, either a path to a kernel
      source tree or a handle in <series>:<package> format. If not
      specified the current working directory is used.

Examples:
  $ cranky chroot create-base bionic:linux
      Build a clean sbuilder chroot for use in bionic build etc.

  $ cranky chroot create-session configs bionic:linux
      Build a chroot session with the appropriate build-depends and cross compilers
      to allow update of configurations for bionic:linux.

  $ cranky chroot run bionic:linux -- cranky close
      Run cranky close under the chroot session.

  $ cranky chroot destroy-session configs bionic:linux
      Destroy the specified chroot session.
EOF

	exit 2
}

# MAIN:
[ "$#" -lt 1 ] && usage
cmd="$1"
shift
case "$cmd" in
create-base)
	if [ "$#" -eq 0 ]; then
		set - "$@" "$PWD"
	elif [ "$#" -ne 1 ]; then
		echo "Usage: $P $cmd [<handle>]" 1>&2
		exit 1
	fi
	session=
	handle="$1"
	;;
create-session|map-session|destroy-session)
	if [ "$#" -eq 1 ]; then
		set - "$@" "$PWD"
	elif [ "$#" -ne 2 ]; then
		echo "Usage: $P $cmd <sources|configs> [<handle>]" 1>&2
		exit 1
	fi
	session="$1"
	handle="$2"
	case "$session" in
	sources|configs)	;;
	*)
		echo "$P $cmd: $session -- invalid session requested (sources or configs)" 1>&2
		exit 1
		;;
	esac
	;;
run)
	if [ "$1" = "--" ]; then
		set - "$PWD" "$@"
	fi
	if [ "$2" != '--' ]; then
		echo "Usage: $P $cmd [<handle>] -- <command ...>" 1>&2
		exit 1
	fi
	session="configs" # XXX: this likely should be its own session type.
	handle="$1"
	shift 2
	;;
*)
	usage
	;;
esac

# NOTE: we require the user to tell us which session type they are needing
#       but in the short term we are assuming we can make do with just the
#       one shared session.  If that should change, then we already have
#       the user supplying the required information so at least the UI will
#       not change underneath them.  Map all the known sessions to a shared
#       session.
case "$session" in
sources|configs)	session="sources" ;;
esac

series_source=$("$C" shell-helper handle-to-series-source "$handle")
if [ "$series_source" = "" ]; then
	echo "$0: $handle: unknown series/package" 1>&2
	exit 1
fi
series=${series_source% *}
src=${series_source#* }
# NOTE: currently all trees are assume to be able to be built in the
#       linux package.
src='linux'

# precise chroots don't get updates anymore, use trusty instead
if [ "$series" = "precise" ]; then
	series="trusty"
fi

OUT_SESSION=
trap out INT TERM EXIT HUP

case "$cmd" in
create-base)
	if base_chroot_available "$series" "$chroot_arch"; then
		chroot_update "$RET"
	else
		base_chroot_create "$series" "$chroot_arch"
	fi
	;;
create-session)
	if session_chroot_available "$series" "$chroot_arch" "$src" "$session"; then
		chroot_update "$RET"
	else
		session_chroot_create "$series" "$chroot_arch" "$src" "$session"
	fi
	;;
map-session)
	if session_chroot_available "$series" "$chroot_arch" "$src" "$session"; then
		echo "$RET"
	else
		echo "$P: No chroot session available for $series:$src" 1>&2
		echo "Use \"$P create-session\" to create one" 1>&2
		exit 1
	fi
	;;
run)
	if session_chroot_available "$series" "$chroot_arch" "$src" "$session"; then
		schroot -p -r -c "$RET" -- "$@"
	else
		echo "$P: No chroot session available for $series:$src" 1>&2
		echo "Use \"$P create-session\" to create one" 1>&2
		exit 1
	fi
	;;
destroy-session)
	if session_chroot_available "$series" "$chroot_arch" "$src" "$session"; then
		schroot -e -c "$RET"
	else
		echo "$P: No chroot session available for $series:$src" 1>&2
		exit 1
	fi
	;;
esac
