#!/bin/bash
#
# cranky helper-wrapper
#

cmd=$(basename "$0")
cranky_root=$(dirname "$C")

if [ ! -d debian ]; then
	echo "$P: should be run in a source package tree" 1>&2
	exit 1
fi

SCRIPTS="debian/scripts/helpers/$cmd $cranky_root/master-helpers/$cmd"
if [ -f debian/debian.env ] ; then
	# shellcheck disable=SC1091
	. debian/debian.env
	SCRIPTS="$DEBIAN/scripts/helpers/$cmd $SCRIPTS"
fi

script=""
for s in $SCRIPTS; do
	if [ -x "$s" ] ; then
		script="$s"
		break;
	fi
done

if [ -z "$script" ] ; then
	echo "$0: $cmd: helper not found" 1>&2
	exit 1
fi

# Assemble the schroot command
session=$("$C" chroot map-session configs .)
chroot_cmd=
if [ "$session" = "$(printf '%q' "$session")" ]; then
	chroot_cmd="schroot -r -c $session --"
else
	echo "Error: chroot command was not set." \
	     "Invalid chroot session: \"$session\"" >&2
	exit 1
fi

#
# $CHROOT is supposed to be used unquoted at the beginning of every
# commands that needs to run inside the corresponding chroot.
#
C="$C" P="$P" CHROOT="$chroot_cmd" exec "$script" "$@"
