#!/bin/bash -eu

function debug_log()
{
	[ "$debug" = "0" ] || echo "$*"
}

function usage()
{
	cat <<EOF
Usage: ${P:-$(basename "$0")} [-h] [-f] [-v]

Tag the current Ubuntu kernel git tree with the correct version tag.

Optional arguments:
  -h, --help     Show this help message and exit.
  -f, --force    Tag the topmost commit even if its subject is not in the
                 expected format. Also replace a tag if it already exists.
  -v, --verbose  Show extra info when running.
EOF
	exit 2
}

debug=0
force=0
unsigned=0
while [ "${#}" -gt 0 ] ; do
	case "${1}" in
		-h|--help)
			usage
			;;
		-v|--verbose)
			debug=1
			;;
		-f|--force)
			force=1
			;;
		-u|--unsigned)
			unsigned=1
			;;
		*)
			echo "error: Unrecognized argument ${1}" >&2
			usage
			;;
	esac
	shift
done

if [ -f debian/debian.env ] ; then
	# shellcheck disable=SC1091
	. debian/debian.env
	if [ -z "${DEBIAN:-}" ] ; then
		echo "error: Can't find 'DEBIAN' variable in debian/debian.env" >&2
		exit 1
	fi
	debug_log "DEBIAN: $DEBIAN"

	changelog_file="${DEBIAN}/changelog"

elif [ -f update-version ] ; then
	# This is a dependent package repo
	changelog_file=debian/changelog

else
	echo "error: No debian/debian.env or update-version script found. Is this an Ubuntu kernel source tree?" >&2
	exit 1
fi

debug_log "Changelog file: $changelog_file"

# Check if changelog is open
series=$(dpkg-parsechangelog -l"$changelog_file" -SDistribution)
if [ "$series" = 'UNRELEASED' ]; then
        echo "error: changelog isn't properly closed. Do you need to run cranky close first?" >&2
        exit 1
fi

if ! git show --name-only --format= | grep "$changelog_file" > /dev/null ; then
	echo "error: No delta in $changelog_file in latest commit" >&2
	echo "Are you sure the topmost commit is a closing commit?" >&2
	exit 1
fi

package=$(dpkg-parsechangelog -l"$changelog_file" -SSource)
debug_log "Package: $package"

new_version=$(dpkg-parsechangelog -SVersion -l"$changelog_file")
debug_log "Newest version: $new_version"

prefix=${package#linux}
prefix=${prefix#-meta}
prefix=${prefix#-signed}
prefix=${prefix#-restricted-modules}
prefix=${prefix#-backports-modules-3.2.0}
prefix=Ubuntu${prefix}-
debug_log "Tag Prefix: $prefix"

new_tag_unfixed="$prefix$new_version"
debug_log "Tag message: $new_tag_unfixed"

if [ "$(git log --format=%s -1)" != "UBUNTU: $new_tag_unfixed" ] ; then
	echo "error: Topmost commit subject does not include the right content" >&2
	echo "Closing commit subject should be:" >&2
	echo "   UBUNTU: $new_tag_unfixed" >&2
	if [ $force -eq 0 ] ; then
		echo "Use -f, --force to tag the commit anyways" >&2
		exit 1
	else
		echo "(--force specified - continuing anyway)"
	fi
else
	debug_log "commit subject looks OK"
fi

new_tag_fixed="${new_tag_unfixed//\~/_}"
debug_log "New tag: $new_tag_fixed"

if git rev-parse "${new_tag_fixed}" >/dev/null 2>&1 ; then
	echo "error: Tag '${new_tag_fixed}' exists already" >&2
	if [ $force -eq 0 ] ; then
		echo "Use -f, --force to replace it" >&2
		exit 1
	else
		echo "(--force specified - continuing anyway)"
	fi
fi

if [ $unsigned -eq 0 ] ; then
	echo "(not signing tags)"
	tag_cmd="git tag -f -s -m $new_tag_unfixed $new_tag_fixed"
else
	tag_cmd="git tag -f -m $new_tag_unfixed $new_tag_fixed"
fi

# OK, everything looks good. Tag it.
echo "Tagging with:"
echo " $tag_cmd"

$tag_cmd
