# Makefile to turning .md files into .html files
#
# You will want to 'sudo -H pip install grip' to get the tool used here installed
# on your local system.
#

%.html: %.md
	grip $< --export

all: cranking-the-kernel.html
