#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

report='y'
instance=''
while :
do
	case "$1" in
	--instance)
		instance="$2"
		shift 2
		;;
	--report)
		report=y
		shift 1
		;;
	--no-report)
		report=
		shift 1
		;;
	*)
		break
		;;
	esac
done

if [ "$#" -lt 6 ]; then
	echo "Usage: $0 [--instance <instance>] [--[no-]report] <daemon> ... -- <group> <title> <warn> <alert> ..." 1>&2
	exit 1
fi

daemon="$1"
name=`basename "$1"`
shift
short_instance="${instance#$name}"
case "$short_instance" in
"")	;;
-*)	;;
*)	short_instance="-$short_instance" ;;
esac

legacy_name="$name$instance"
name="$name$short_instance"

# Pull the command line apart, everything before -- is the daemon
# command, the remainder for dashboard-status
declare -a args
while [ "$#" -gt 0 -a "$1" != '--' ]
do
    args[${#args[*]}]="$1"
    shift
done
[ "$1" = '--' ] && shift

# Relative filenames are relative to the directory containing sbin/$0
case "$daemon" in
/*)		;;
*)		daemon="$here/../$daemon" ;;
esac

legacy_lck="/tmp/$legacy_name.lck"
lck="$HOME/.$name.lck"

# If we are using the legacy lock name, then attempt to rename it
# if we are able to then we can use the new name, otherwise retain
# the old.
if [ -f "$legacy_lck" ]; then
	if ! mv "$legacy_lck" "$lck"; then
		lck="$legacy_lck"
	fi
fi

# Start the daemon in the background -- it remains connected to the lockfile
# which keeps the locks in place.
(
	flock -n 9 || exit 1
	echo "Starting $(date --utc)"
	"$daemon" "${args[@]}" &
) 9>"$lck"

if [ "$report" ]; then
	# Attempt to re-grab an exclusive lock, if this succeeds then the daemon has
	# failed to start.  Timeout after 5s.
	flock -w 5 -x "$lck" -c "exit 0" || \
	    $here/../dashboard/dashboard-status "cron-start-$name" "$@"
fi
