#!/bin/sh

if [ "$#" -lt 3 ]; then
	echo "Usage: <key> <timeout> <cmd>" 2>&1
	exit 1
fi
key="$1"
timeout="$2"
shift 2

exec flock -n $HOME/.lock-$key $HOME/kteam-tools/sbin/oops-stream $key timeout $timeout "$@"
