#!/bin/bash

error_ok=999
if [ "$1" = "--error-ok" ]; then
	error_ok="$2"
	shift 2
fi

key="$1"
shift

[ "$key" = "" ] && key="UNKNOWN"

here=$(dirname "$(readlink -f "${0}")")
oops=$(mktemp "$HOME/public_html/oops/$key.XXXXXXXXXX")
chmod 644 "$oops"

# { { { { someprog; echo $? >&3; } | filter >&4; } 3>&1; } | { read xs; exit $xs; } } 4>&1
set -o pipefail

{
	echo "RUNNING: $@"
	"$@"
	rc="$?"
	echo "EXIT: rc=<$rc>"
} >"$oops" 2>&1

if [ "$rc" = "$error_ok" ]; then
	tail -2 "$oops" | head -1
	rm -f "$oops"

elif [ "$rc" != 0 ]; then
	echo "OOPS: http://kernel.ubuntu.com/~kernel-ppa/oops/$(basename "$oops")"

else
	rm -f "$oops"
fi

exit "$rc"
