#!/usr/bin/python
#==============================================================================
# Author: Stefan Bader <stefan.bader@canonical.com>
# Copyright (C) 2010
#
# This script is distributed under the terms and conditions of the GNU General
# Public License, Version 3 or later. See http://www.gnu.org/copyleft/gpl.html
# for details.
#==============================================================================
import sys, os, optparse, re
from subprocess import *
from ktl.shell                          import sh, ShellError

#------------------------------------------------------------------------------
# Libraries shared by all kteam-tools will be found here (../lib)
#------------------------------------------------------------------------------
common_lib = os.path.dirname(os.path.abspath(sys.argv[0]))
common_lib = os.path.dirname(common_lib)
common_lib = os.path.join(common_lib, "lib")
sys.path.insert(0, common_lib)

from buildenv_lib import *

#------------------------------------------------------------------------------
# Setup the command line parser and run it.
#------------------------------------------------------------------------------
parser = optparse.OptionParser("Usage: %prog [options]")
dsc    = "Starts a new release and commits the changes to git (also will "
dsc   += "optionally fetch the ABI files)."
parser.set_description(dsc)
parser.add_option(
	"--host", action="store", dest="tgthost", default=None,
	help="hostname to be passed to maint-getabis (default is to use the "
	     "one maint-getabis defaults to)")
parser.add_option(
	"--dry-run", action="store_true", dest="dryrun", default=False,
	help="only print what would be done")
parser.add_option(
	"--local", action="store_true", dest="local", default=False,
	help="pass --local to maint-getabis, to extract the packages "
	     "locally")
parser.add_option(
	"--ckt-ppa", action="store_true", dest="cktppa", default=False,
	help="pass --ckt-ppa to maint-getabis, to add c-k-t ppa as an "
	     "abi source")
epilog = "Example: user@test:~/ubuntu-oneiric$ %s " % (parser.get_prog_name())
epilog += "--local --ckt-ppa"
parser.epilog = epilog
(opts, args) = parser.parse_args()


#
# Make sure the DEBEMAIL is the right domain (default @canonical.com)
#
mailenforce = os.getenv("MAINT_STARTNEWRELEASE_MAILENFORCE")
if not mailenforce:
	mailenforce = "@canonical.com"

debem = os.getenv("DEBEMAIL")
if debem is not None:
	if mailenforce not in debem:
		print 'DEBEMAIL does not contain', mailenforce
		sys.exit(1)

#------------------------------------------------------------------------------
# Find the abstracted debian directory and make sure it is there (IOW we are
# in the right directory).
#------------------------------------------------------------------------------
debian_dir = GetDebianDir()
if not os.path.isdir(debian_dir):
	print "EE:", debian_dir, "not found! Must be called from toplevel",
	print "directory."
	sys.exit(1)

(srcpkg, version, pocket, flags) = GetPackageInfo()
if '~' in version:
    lts_version = version.split('~')[1]
version = version.split("~")[0]
kversion = version.split("-")[0]
kabi, krel = version.split("-")[1].split(".")

#------------------------------------------------------------------------------
# Make sure the changelog is not locally modified.
#------------------------------------------------------------------------------
changelog = os.path.join(debian_dir, "changelog")
if GitDiff(changelog):
	print "EE:", changelog, "has been locally modified!"
	sys.exit(1)

#------------------------------------------------------------------------------
# Check whether the current release is not released. In that case there is
# nothing to do but to warn.
#------------------------------------------------------------------------------
if pocket == "UNRELEASED":
	print("WW: %s-%s" % (srcpkg, version))
	print(" ")
	print("    The tree is in a state (UNRELEASED) that does not require a 'start new release'. ")
	print("    Patches may be applied directly to the branch as it currently stands.")
	sys.exit(0)

#------------------------------------------------------------------------------
# Try to make sure we've run fdr clean
#------------------------------------------------------------------------------
if not os.path.isfile("debian/control"):
	print "EE: debian control file not found - do you need to run 'fakeroot debian/rules clean'?"
	sys.exit(1)

#------------------------------------------------------------------------------
# Only need to take care of the ABI files for the linux-kernel package.
#------------------------------------------------------------------------------
if os.path.isdir(os.path.join(debian_dir, "abi")):
	#----------------------------------------------------------------------
	# Try to get the new ABI files (note that version is not incremented,
	# yet).
	#----------------------------------------------------------------------
	for path in sys.path:
		cmd = os.path.join(path, "maint-getabis")
		if os.path.isfile(cmd):
			break
	else:
		print "EE: maint-getabis not found!"
		sys.exit(1)
	if opts.tgthost:
		cmd += " --host " + opts.tgthost
	if opts.dryrun:
		cmd += " --dry-run"
	if opts.local:
		cmd += " --local"
	if opts.cktppa:
		cmd += " --ckt-ppa"
        if "-lts-" in srcpkg:
            v = "Ubuntu-lts-" + version + '_' + lts_version
        elif "-raspi2" in srcpkg:
            v = "Ubuntu-raspi2-" + version
        elif "-snapdragon" in srcpkg:
            v = "Ubuntu-snapdragon-" + version
        elif "-ti-omap4" in srcpkg:
            v = "Ubuntu-ti-omap4-" + version
        else:
            v = "Ubuntu-" + version
	print(cmd + " " + v)
	(rc, output) = sh(cmd + " " + v)

	#----------------------------------------------------------------------
	# Remove the old ABI files (as the changelog is not modified, yet,
	# this should be the version number before. Then add the new abi
	# directory to be committed.
	#----------------------------------------------------------------------
	print "II: Removing old ABI files and adding the new ones"
        v = GetPackageInfo(prev=True)[1]
        v = v.split("~")[0]
	old_abi_dir = os.path.join(
		debian_dir,
		"abi",
                v
	)
	if not opts.dryrun:
		(rc, output) = sh("git rm --quiet -rf " + old_abi_dir, ignore_result=True)
		(rc, output) = sh("rm -rf " + old_abi_dir, ignore_result=True)
		(rc, output) = sh("git add " + os.path.join(debian_dir, "abi", version))

#------------------------------------------------------------------------------
# Next step is to create a new changelog with the new header first and the
# remainder appended from the old one.
#------------------------------------------------------------------------------
if opts.dryrun:
	print "Would call fakeroot debian/rules here"
else:
	(rc, output) = sh("fakeroot debian/rules startnewrelease")
	(rc, output) = sh("git add " + changelog)
	(rc, output) = sh("git commit -s -F debian/commit-templates/newrelease")

#------------------------------------------------------------------------------
# Finally add the changelog and commit everything.
#------------------------------------------------------------------------------
print "\n\n***** Now please inspect the commit before pushing *****"
