#!/usr/bin/python
from __future__ import print_function

import os
import json

with open('trusty.cache', 'r') as rfd:
    tmp = json.load(rfd)
    chg = False

    # This result is created by a badly triggered failed job on ppc64el.
    if '3.19.0-33.38~14.04.1 linux-meta' in tmp['results']:
        del tmp['results']['3.19.0-33.38~14.04.1 linux-meta']
        chg = True

    if chg:
        with open('trusty.cache.new', 'w') as wfd:
            json.dump(tmp, wfd, indent=2)
        os.rename('trusty.cache.new', 'trusty.cache')
