#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

if [ "$#" -ne 2 ]; then
	echo "Usage: $0 <pocket> <linux meta package>" 1>&2
	exit 1
fi
pocket="$1"
linux_meta="$2"

series="${pocket%-*}"
pocket="${pocket#$series-}"
linux=`echo "$linux_meta" | sed -e 's/^linux-meta/linux/g'`

triggers=''
for package in "$linux_meta" "$linux"
do
	#echo "pocket<$pocket> series<$series> package<$package>" 1>&2
	version=`"$here/../cve-tools/cves-kernel-versions" "$pocket" "$series" "$package"`
	if [ "$version" = 'None' ]; then
		echo "$package: version unknown in $pocket" 1>&2
		exit 1
	fi
	triggers="$triggers $package/$version"
done
echo "adt-commands: $series-$pocket $triggers" 1>&2
$0-payload "$series" $triggers
