#!/usr/bin/python2
from __future__ import print_function

import yaml
import sys

with open(sys.argv[1]) as jfd:
    tmp = yaml.load(jfd)

tests = {}

for source in tmp['sources']:
    if source['source'] not in ('linux', 'linux-meta'):
        continue
    if 'policy_info' not in source:
        continue
    if 'autopkgtest' not in source['policy_info']:
        continue

    for key in source['policy_info']['autopkgtest'].keys():
        if '/' in key:
            bits = key.split('/')
        else:
            bits = key.split()
        src = bits[0]
        tests[src] = True

for key in sorted(tests.keys()):
    print("            '" + key + "',")
