#!/usr/bin/python2
from __future__ import print_function

import yaml
import sys

with open(sys.argv[1]) as jfd:
    tmp = yaml.load(jfd)

tests = {}

for source in tmp['sources']:
    if source['source'] not in ('linux', 'linux-meta'):
        continue
    if 'tests' not in source:
        continue
    if 'autopkgtest' not in source['tests']:
        continue

    for key in source['tests']['autopkgtest'].keys():
        (src, ver) = key.split()
        tests[src] = True

for key in sorted(tests.keys()):
    print("            '" + key + "',")
