#!/usr/bin/python
from __future__ import print_function

import json
import sys

# Read in the package/architecture relationships.
with open("package-relation.json") as seedf:
    package_cache = json.load(seedf)

series = sys.argv[1]
triggers = sys.argv[2:]

(master_package, master_version) = triggers[0].split('/')

# Read in the series cache.
with open(series + ".cache") as cachef:
    series_cache = json.load(cachef)

# Generate commands to retrigger all missing tests.
for (states, message) in ((None, 'all'), (['MISS'], 'missing'), (['REGR'], 'regressing')):
    print("# " + series + " " + master_package + " retrigger " + message)

    mkey = '-'.join((series, master_package))
    if mkey not in series_cache['current']:
        continue

    if not states:
        states = series_cache['current'][mkey].keys()
        
    want = {}
    for state in states:
        if state not in series_cache['current'][mkey]:
            continue
        current = series_cache['current'][mkey][state]
        for trigger in triggers:
            (package, version) = trigger.split('/')
            key = '-'.join((series, package))
            #print(package, version, key)
            if mkey in package_cache['cache-latest']:
                for package in package_cache['cache-latest'][mkey]:
                    #print(package, mpkg)
                    for tpkg in package_cache['cache-latest'][mkey][package]:
                        #print(package, mpkg, tpkg)
                        if tpkg in current:
                            archs = []
                            for arch in ['amd64', 'i386', 'armhf', 'ppc64el']:
                                if arch in current[tpkg]:
                                    archs.append(arch)
                            if len(archs) > 0:
                                tmp = want.setdefault(' '.join(archs), {}).setdefault(tpkg, [])
                                if trigger not in tmp:
                                    tmp.append(trigger)

    for archs in want:
        forms = {}
        for key in want[archs]:
            forms[' '.join(want[archs][key])] = True

        packages_form = {}
        for form in forms:
            for key in want[archs]:
                if ' '.join(want[archs][key]) == form:
                    packages_form.setdefault(form, []).append(key)

        for form in forms:
            if form in packages_form:
                cmd = "run-autopkgtest -s " + series
                for arch in archs.split():
                    cmd += ' -a ' + arch
                for trigger in form.split():
                    cmd += ' --trigger ' + trigger
                cmd += ' ' + ' '.join(sorted(packages_form[form]))

                print(cmd)

    print("")
