#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

if [ "$#" != '2' ]; then
	echo "Usage: $0 <html> <britney cache>" 1>&2
	exit 1
fi
html="$1"
britney="$2"

mkdir -p "$html"
(
	cd "$html" || exit 1
	"$here/adt-update" "$here/adt-matrix.conf" - "$britney"
)
mkdir -p "$html/canonical-kernel-team--unstable"

(
	cd "$html/canonical-kernel-team--unstable" || exit 1
	ln -sf ../package-relation.json .

	"$here/adt-update" "$here/adt-matrix.conf.d/canonical-kernel-team--unstable" canonical-kernel-team/unstable -
)
