#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <britney state directory>" 1>&2
fi

britney="$1"

# Update package-relation.json
[ ! -f package-relation.json ] && \
	cp "$here/package-relation.json-initial" package-relation.json
while read series package
do
	echo "$series $package $britney/$series.migration"
done <"$here/adt-matrix.conf" | \
	"$here/adt-seed-accumulate"

while read series package
do
	[ "$series" = '#' ] && continue

	case "$package" in
	linux-meta*)
		migration=`awk '/^'"$series $package"' / { print $NF }' "$britney/overall.txt"`
		[ "$migration" = '' ] && migration="MIGRATED"
		;;
	*)
		migration="-"
		;;
	esac
	echo "$series $package $migration"
done <"$here/adt-matrix.conf" | \
	"$here/adt-matrix"
