#!/bin/bash

here=$(dirname $(readlink -f "$0"))

if [ "$#" -ne 2 ]; then
	echo "Usage: $0 <data-directory> <published-info-directory>" 1>&2
	exit 1
fi
data="$(readlink -e "$1")"
out="$(readlink -e "$2")"

echo "$(date): starting"

cd "$out" || exit "$?"

# Update the data and tooling.
if [ ! -d "$data/kteam-tools" ]; then
	git clone git://git.launchpad.net/~canonical-kernel/+git/kteam-tools "$data/kteam-tools" || exit "$?"
else
	(
		cd "$data/kteam-tools" || exit 1
		git fetch --prune origin
		git reset --hard origin/master
	) || exit "$?"
fi
if [ ! -d "$data/kernel-versions" ]; then
	git clone git://git.launchpad.net/~canonical-kernel/+git/kernel-versions "$data/kernel-versions" || exit "$?"
else
	(
		cd "$data/kernel-versions" || exit 1
		git fetch --prune origin
		git reset --hard origin/main
	) || exit "$?"
fi

# Update and convert branches...
{
	(
		cd "$data/kteam-tools" || exit 1
		git for-each-ref --format "kernel-series - $data/kteam-tools %(refname) %(objectname) info/kernel-series.yaml" refs/remotes/origin/master
		git for-each-ref --format "sru-cycle - $data/kteam-tools %(refname) %(objectname) info/sru-cycle.yaml" refs/remotes/origin/master
		git for-each-ref --format "signing-config - $data/kteam-tools %(refname) %(objectname) info/signing-config.yaml" refs/remotes/origin/master
	)
	(
		cd "$data/kernel-versions" || exit 1
		main=$(git for-each-ref --format "$data/kernel-versions kernel-series %(objectname) %(refname)" refs/remotes/origin/main)
		if [ "$main" ]; then
			objectname=$(git for-each-ref --format "%(objectname)" refs/remotes/origin/main)
			git ls-tree --name-only -r refs/remotes/origin/main | grep info/kernel-series.yaml | \
			while read ks
			do
				case "$ks" in
				tip/*)	continue ;;
				esac
				variant="$(echo "$ks" | sed -e "s@^complete/@@" -e "s@/.*@@")"
				echo "kernel-series @$variant $data/kernel-versions refs/remotes/origin/main $objectname $ks"
			done
		else
			git for-each-ref --format "kernel-series @%(refname:lstrip=-1) $data/kernel-versions %(refname) %(objectname) info/kernel-series.yaml" refs/remotes/origin | grep -v -- "-next$"
		fi
	)
} | \
while read filename variant repo refname objectname objectpath x
do
	case "$repo:$refname" in
	*/kernel-versions:*/HEAD)		continue ;;
	*/kernel-versions:*/master)		continue ;;
	esac

	if [ "$variant" = "-" ]; then
		variant=""
	fi
	objectname_file="$out/.$filename$variant.on"
	#echo "REPO<$repo> ON<$objectname> RN<$refname> objectname_file<$objectname_file>"
	objectname_existing="$(cat "$objectname_file" 2>/dev/null)"
	if [ "$objectname_existing" = "$objectname" ]; then
		continue
	fi
	echo "II: upstream $(basename "$repo"):$(basename "$refname") $filename.yaml$variant tip changed ..."
	(
		cd "$repo" || exit 1
		git show "$refname:$objectpath" >"$out/$filename.yaml.new" || exit 0
		if [ -e "$out/$filename.yaml$variant" ]; then
			cmp -s "$out/$filename.yaml$variant" "$out/$filename.yaml.new" && exit 0
		fi
		echo "II: upstream $(basename "$repo"):$(basename "$refname") $filename.yaml$variant data changed ..."
		"$here/ks-convert" "$out/$filename.yaml.new" "$out/$filename.json.new" || exit 0
		gzip -9 <"$out/$filename.json.new" >"$out/$filename.json.gz.new"
		mv -f "$out/$filename.yaml.new" "$out/$filename.yaml$variant"
		mv -f "$out/$filename.json.new" "$out/$filename.json$variant"
		mv -f "$out/$filename.json.gz.new" "$out/$filename.json.gz$variant"
	) || exit "$?"
	echo "$objectname" >"$objectname_file"
done

echo "$(date): complete"
