#!/bin/bash

here=$(dirname $(readlink -f "$0"))

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <published-info-directory>" 1>&2
	exit 1
fi
out="$1"

echo "$(date): starting"

cd "$out" || exit "$?"

# Update the data and tooling.
(
	cd "$here" || exit "$?"

	git fetch origin
	git reset --hard origin/master
) || exit "$?"

esum=$(cat "split/.kernel-series.yaml" 2>/dev/null)
nsum=$(cat "$0" "$here/ks-split" "kernel-series.yaml" | md5sum | awk '{print($1);}')
if [ "$esum" != "$nsum" ]; then
	echo "II: upstream kernel-series.yaml changed ..."
	"$here/ks-split" "kernel-series.yaml" "split" && cp "kernel-series.yaml" "split/.kernel-series.yaml"
	ls -1t "split" | tail -n +10 | \
	while IFS= read -r old
	do
		rm -rf "split/$old"
	done
	echo "$nsum" >"split/.kernel-series.yaml"
fi

echo "$(date): complete"
