#!/bin/bash

CDIR="`dirname $0`"

. "${CDIR}/scripts/chroot-defs.conf"

MIRROR=$1
PORTS_MIRROR=$2

for RELEASE in ${releases[@]}
do
	if ! not_expired_release ${RELEASE}
	then
		echo ${RELEASE} is expired.
		continue
	fi

	${CDIR}/make_release ${RELEASE} ${MIRROR} ${PORTS_MIRROR}
done
