#!/bin/bash

# git-stable-extag
#
# Run from inside of a linux upstream repository to
# export all the patches for a given upstream stable
# release.
#
# Author: Kamal Mostafa <kamal@canonical.com>

[ "$1" = "-l" ] && {
        listmode=1
        shift
}

tag="$1"

set -e

info=$(git describe "${tag}^")
## e.g. tag=v4.14.54 yields v4.14.53-61-g88b01cac4add
info=${info%-*} # strip sha
prevtag=${info%-*}
thiscount=$(( ${info#*-} + 1 ))

authdate=$(git log -1 --no-decorate --pretty='%ai' $tag)
authdate="${authdate%% *}"

echo "$authdate $tag    [$thiscount]"

[ "$listmode" = "1" ] && exit 0

outdir="/tmp/$tag"
[ -d "$outdir" ] && {
        echo "E: $outdir already exists"
        exit 1
}

echo git format-patch -k -o "$outdir" "$prevtag..$tag"
git format-patch -k -o "$outdir" "$prevtag..$tag"

