[project]
name = "ckt-info"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.8"

# TODO: Is there a better way to do this?
[tool.setuptools.package-data]
ckt_info = [
  "info/*.yaml",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
