#!/usr/bin/python

from __future__ import print_function

import ast
import urllib2
import re
import os
import sys

from operator import itemgetter
from optparse import OptionParser

parser = OptionParser()
parser.add_option("-f", "--removed", dest="removed", action="append",
                  help="mark package as removed from the primary release")

(options, args) = parser.parse_args()

#url = 'http://jenkins.qa.ubuntu.com/view/DKMS/view/U%20-generic'
#url = 'http://jenkins.qa.ubuntu.com/view/DKMS/view/T%20Proposed%20-generic/'

versions = zip(args[0::2], args[1::2])

jstate = {}
jseen = {}
count = 0
for (url, vreport) in versions:
    count += 1
    tree = ast.literal_eval(urllib2.urlopen(url + '/api/python?depth=2').read().decode('utf-8'))

    for job in tree['jobs']:
        #print(job['name'])
        #print(job['description'])
        name = job['name'].split('-').pop()

        #print(job['builds'][0])
        seen = False
        # Ensure we treat runs in latest build in the latest kernel first order.
        for build in sorted(job['builds'], key=itemgetter('number', 'timestamp'), reverse=True):
            if 'description' not in build or not build['description']:
                continue
            (kver, pver) = build['description'].split(' ')
            (pkg, pver) = pver.split('/')
            if pkg == '':
                continue

            if vreport == 'latest':
                vreport = kver

            if kver != vreport and not seen:
                continue
            seen = True

            if count == 1 and kver == vreport:
                jseen[name] = True

            if build['result'] == 'SUCCESS':
                status = 'GOOD'
            elif build['result'] == None:
                status = 'MISSING'
            else:
                status = 'FAIL-ALWAYS'

            ##print(name, kver, pver, status)

            if name not in jstate:
                jstate[name] = status
                continue

            # If this is the latest report, and we are missing a job, call it all
            # missing
            if kver == vreport and jstate[name] == 'GOOD' and status == 'MISSING':
                jstate[name] = 'MISSING'

            # Work out if this has ever worked, if so it is a regression.
            if jstate[name] == 'FAIL-ALWAYS' and status == 'GOOD':
                jstate[name] = 'FAIL-REGRESSION(' + kver + ')'
                break

        if name not in jstate:
            jstate[name] = 'MISSING'

for package in jstate:
    if package not in jseen:
        if options.removed and package in options.removed:
            jstate[package] = 'REMOVED'
        else:
            jstate[package] = 'MISSING'
                
for package in sorted(jstate):
    print(package, jstate[package])
