#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

out="$HOME/public_html/info/dkms"
mkdir -p "$out"

err=0

# Generate each series summary.
while read -r file line
do
	# Make sure we don't stray out of the approved space.
	case "$file" in
	*/*)	continue ;;
	esac

	ofile="$out/$file"
	echo "- $line" | "$here/dkms-jenkins-matrix" >"$ofile.new" \
		--urlmap http://d-jenkins.ubuntu-ci:8080/ http://jenkins.qa.ubuntu.com/
	[ "$?" -ne 0 ] && err=1
	mv -f "$ofile.new" "$ofile"

	ofile="$out/int-$file"
	echo "- $line" | "$here/dkms-jenkins-matrix" >"$ofile.new"
	[ "$?" -ne 0 ] && err=1
	mv -f "$ofile.new" "$ofile"
done <"$here/dkms-jenkins-matrix.conf"

# Generate the common summary.
ofile="$out/dkms-matrix.html"
"$here/dkms-jenkins-matrix" --versions 3 <"$here/dkms-jenkins-matrix.conf" >"$ofile.new" \
	--urlmap http://d-jenkins.ubuntu-ci:8080/ http://jenkins.qa.ubuntu.com/
[ "$?" -ne 0 ] && err=1
mv -f "$ofile.new" "$ofile"

ofile="$out/int-matrix.html"
while read line; do echo "int-$line"; done <"$here/dkms-jenkins-matrix.conf" | \
	"$here/dkms-jenkins-matrix" --versions 3 >"$ofile.new"
[ "$?" -ne 0 ] && err=1
mv -f "$ofile.new" "$ofile"

ofile="$out/regressions.txt"
"$here/dkms-jenkins-matrix" --regressions <"$here/dkms-jenkins-matrix.conf" >"$ofile.new"
[ "$?" -ne 0 ] && err=1
mv -f "$ofile.new" "$ofile"

exit "$err"
