#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

out="public_html/info/dkms-matrix.html"

"$here/dkms-jenkins-matrix" \
	"https://jenkins.qa.ubuntu.com/view/DKMS/view/U%20KT-PPA%20-generic/" \
	"https://jenkins.qa.ubuntu.com/view/DKMS/view/V%20KT-PPA%20-generic/" \
    >"$out.new"

mv -f "$out.new" "$out"
