#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

out="public_html/info/dkms-matrix.html"

"$here/dkms-jenkins-matrix" <"$here/dkms-jenkins-matrix.conf" >"$out.new"

mv -f "$out.new" "$out"
