#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

cd "$here" || exit 1

if [ "$#" = 0 ]; then
	echo "Usage: $0 <cmd>" 1>&2
	exit 1
fi

cmd="$1"
shift

mkdir -p "$HOME/logs"

lck="/tmp/$cmd.lck"
# Start the daemon in the background -- it remains connected to the lockfile
# which keeps the locks in place.
(
	flock -n 9 || exit 1
	echo "Starting `date`"
	"$here/$cmd" "$@" &
) 9>"$lck" >>"$HOME/logs/$cmd.log" 2>&1

# Attempt to re-grab an exclusive lock, if this succeeds then the daemon has
# failed to start.  Timeout after 5s.
flock -w 5 -x "$lck" -c "exit 0" || \
    $HOME/bin/dashboard-status "$cmd" "$@"
