#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

# Cleanup the daily build
for which in "$HOME/public_html/mainline"/*/current
do
	which=`dirname "$which"`
	"$here/cleanup-daily-one" "$which"
done

exit 0
