#! /bin/bash
P="cod-mainline-native-build"

if [ "$#" -ne 2 ]; then
	echo "Usage: $0 <ppa> <changes>" 1>&2
	exit 1
fi

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

cd "$HOME/incoming/upload/mainline-native-queue" || exit 1

ppa="$1"
prefix="$2"

P="$P ($ppa)"

changes="${prefix}_source.changes"

if [ ! -f "$changes" ]; then
	echo "$P: $changes: changes file missing?" 1>&2
	exit 1
fi

echo "$P: Uploading source ..."
dput "ppa:ubuntu-kernel-test/ubuntu/$ppa"

# Make a nice clean results directory ...
mkdir -p "$prefix"
cd "$prefix" || exit 1

# Monitor the PPA and download the results.
echo "$P: Monitoring build in $ppa ..."
"$here/cod-mainline-native-build-ppa" "$ppa"

# Copy the results out ...
echo "$P: Copying out results ..."
