#!/bin/bash
P="cod-changeset-trigger"

set -e

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

. "$here/lib-build"

# Ensure we have our state directory.
mkdir -p "$master_main/state/changeset"

#
# UBUNTU SOURCE: tips of the ubuntu trees et al
#
now_tm=`date +%s`
date=`date +%Y%m%d%H%M`

repo="linux"

# Work out where we are going to push the tags et al to.
repo_remote_url "crack-push"; push_url="$RET"

while read series package branch
do
	current="${series}_${package}_${branch}"
	curr="$master_main/state/changeset/$current"
	remote="$series--$package"
	branch="$remote/$branch"

	repo_update_remote "$repo" "$remote"

	tip=$( cd "$master_main/$repo" && git log -1 --format=%H "$branch" )
	if [ ! -f "$curr" ]; then
		echo "previously unscanned tip, only rebuilding tip"
		prev=$( cd "$master_main/$repo" && git log -1 --format=%H "$branch^" )
		echo "$prev" >"$curr.new"
		mv -f "$curr.new" "$curr"
	fi
	prev=$( cat "$curr" )

	echo "repo<$repo> branch<$branch> tip<$tip> prev<$prev> curr<$curr>"

	# If the tip matches our last upload then there is nothing to do.
	if [ "$tip" = "$prev" ]; then
		echo "nominal tip unchanged, skipping"
		continue
	fi

	# If the tip is non-linear we have no idea how far back to go ...
	merge_base=$( cd "$master_main/$repo" && git merge-base "$prev" "$tip" )
	if [ "$merge_base" != "$prev" ]; then
		echo "rebase detected, only rebuilding tip"
		prev="$tip^"
	fi

	(
		cd "$master_main/$repo" || exit 1

		git log "$prev..$tip" | "$here/git-changeset" | \
		while read sha1 changeset title
		do
			# We cannot assume any remote machine has this sha1 so tag it with a
			# temporary name, and publish that into the crack repository.
			tag="cod/changeset/$series/hash--$sha1"
			git tag -d "$tag" || true
			git tag "$tag" "$sha1"

			# Note if this fails the job will fail, but it is better that the job
			# is created and logged so we can rerun it rather than never knowing
			# about it.
			git push --force "$push_url" tag "$tag"

			# Queue up the build.
			"$here/cod-enqueue" "cod-changeset-build" \
				"$series" "$package" "crack" "$tag" "$changeset"
		done
	)
		
	# Commit the new tip.
	echo "$tip" >"$curr.new"
	mv -f "$curr.new" "$curr"

done <<EOL
artful linux master-next
artful linux-raspi2 raspi2
zesty linux master-next
xenial linux master-next
trusty linux master-next
precise linux master-next
EOL

#pre-proposed wily linux master-next linux-meta master -
#pre-proposed utopic linux master-next linux-meta master no-release
#pre-proposed lucid linux master-next linux-meta master no-release
#pre-proposed lucid linux-lbm master no-release
#pre-proposed utopic linux goldfish linux-meta goldfish -
#pre-proposed utopic linux grouper linux-meta grouper -
#pre-proposed utopic linux maguro linux-meta maguro -
#pre-proposed utopic linux mako linux-meta mako -
#pre-proposed utopic linux manta linux-meta manta -
#pre-proposed raring linux-lbm master no-release
#pre-proposed raring linux master-next linux-meta master no-release
