#!/bin/bash
#
# Update virgin repos and mirror them to Launchpad
#

echo "II: $0 $*"

here=$(dirname "$(readlink -f "${0}")")

while read -r primary mirror
do
	"$here/../sbin/oops-stream" "update-virgin" "$here/cod-update-virgin-single" "$primary" "$mirror"
done <<EOL
git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git	linus--linux
git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git	linux-stable
git://people.freedesktop.org/~airlied/linux				airlied--linux
https://gitlab.freedesktop.org/drm/i915/kernel.git			freedesktop--drm-intel
https://gitlab.freedesktop.org/drm/tip.git				freedesktop--drm-tip
EOL
#git://git.infradead.org/debloat-testing.git				infradead--debloat-testing
