#!/bin/bash
P="cod-tags-trigger"

#set -e

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

url="http://people.canonical.com/~kernel/info/kernel-version-map.txt"
url2="http://people.canonical.com/~kernel/info/kernel-version-pockets.txt"

. "$here/lib-build" 

master_tags="$master_state/ubuntu"
tags_list="$master_tags/release-tags"
pockets_list="$master_tags/pocket-versions"
ptags_list="$master_tags/pocket-tags"

# Ensure our master state exists.
mkdir -p "$master_tags"

#
# UBUNTU TAGS: Find all the new Ubuntu release tags.
#
wget -q -O "$tags_list.new" "$url"
wget -q -O "$pockets_list.new" "$url2"

mv "$tags_list.new" "$tags_list"
mv "$pockets_list.new" "$pockets_list"

while read series package vesion pocket
do
	grep "^$series $package $version " "$tags_list"
done <"$pockets_list" | \
	sort -u >"$ptags_list.new"

[ ! -f "$ptags_list" ] && : >"$ptags_list"
diff "$ptags_list" "$ptags_list.new" | \
	awk '/>/' | tac >"$ptags_list.added"

# Commit the list.
mv "$ptags_list.new" "$ptags_list"

# Run the list.
while read added series package package_ver ubuntu_ver mainline_ver
do
	"$here/cod-enqueue" "cod-ubuntu-config" "$series" "$package" "$package_ver" "$ubuntu_ver"
done <"$ptags_list.added"

rm -f "$ptags_list.added"
