#!/bin/bash
P="cod-source-trigger"

set -e

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

. "$here/lib-build"

# Ensure we have our state directory.
mkdir -p "$master_main/state/source"

#
# UBUNTU SOURCE: tips of the ubuntu trees et al
#
now_tm=`date +%s`
date=`date +%Y%m%d%H%M`
while read ppa series repo branch repo2 branch2 flags
do
	current="${repo}_${series}_${branch}"
	curr="$master_main/state/source/$current"
	branch="$series/$branch"

	repo_update_ubuntu "$repo" "$series"

	# Find the first non-ignored commit, the first real change.
	tip=`cd "$master_main/$repo" && git log "$branch" | awk '
		BEGIN				{ sha1 = "" }
		/^ *UBUNTU: Bump ABI/		{ exit }
		/^commit /			{ if (sha1 != "") { exit };
						  sha1 = $2 }
		/^ *Ignore: *yes/		{ sha1 = "" }
		END				{ print sha1 }
	'`

	release=`cd "$master_main/$repo" && git log "$branch" | awk '
		/^commit /			{ sha1 = $2 }
		/^ *UBUNTU: *Ubuntu-/		{ exit }
		END				{ print sha1 }
	'`
	prev=`cat "$curr" 2>/dev/null || true`

	echo "repo<$repo> branch<$branch> tip<$tip> release<$release> prev<$prev>"
	upload=1

	# If the tip matches our last upload then there is nothing to do.
	if [ "$tip" = "$prev" ]; then
		echo "nominal tip unchanged, skipping"
		upload=0
	fi
		
	# If the tip matches the release commit and those are excluded
	# then there is nothing to do.
	case ",$flags," in
	*,no-release,*)
		if [ "$tip" = "$release" ]; then
			echo "nominal tip represents release, skipping"
			upload=0
		fi
		;;
	esac

	# If we did an upload in the last 12 hours, then it is too soon
	# to upload again.
	if [ -f "$curr" ]; then
		upload_tm=`stat -c %Y "$curr"`
		let update_age="$now_tm-$upload_tm"
		if [ "$update_age" -lt 43200 ]; then
			echo "nominal tip uploaded <12hrs ago ($update_age), skipping"
			upload=0
		fi
	fi

	# If we committed less than 2 hours ago then we might make further
	# updates soon, so hold a little.
	commit_tm=`cd "$master_main/$repo" && 
		git log --pretty=format:%ct "$branch^..$branch" || true`
	if [ "$commit_tm" = '' ]; then
		echo "actual tip does not exist, skipping"
		upload=0
	else
		let commit_age="$now_tm-$commit_tm"
		if [ "$commit_age" -lt 7200 ]; then
			echo "actual tip changed <2hrs ago ($commit_age), skipping"
			upload=0
		fi
	fi

	if [ "$upload" = '0' ]; then
		continue
	fi
	
	# Commit the new tip.
	echo "$tip" >"$curr.new"
	mv -f "$curr.new" "$curr"

	# Queue up the build.
	"$here/cod-enqueue" "A" \
		"$here/cod-source" "$ppa" "$repo" "$series" "$tip" "$date"

	# If we are dealing with linux then we need to ensure that linux-meta
	# is uploaded with an appropriate ABI number.
	if [ "$repo2" = "" ]; then
		continue
	fi

	repo_update_ubuntu "$repo2" "$series"

	current="${repo2}_${series}_${branch2}.ABI"
	curr2="$master_main/state/source/$current"
	branch2="$series/$branch2"

        # Find the abi number for the tip.
        changelog=`cd "$master_main/$repo" && \
                { git cat-file -p "$tip:debian/debian.env" 2>/dev/null ||
                echo "DEBIAN=debian"; } | sed -e 's/DEBIAN=//'
	`
        abi_tip=`cd "$master_main/$repo" && \
                git cat-file -p "$tip:$changelog/changelog" | \
		sed -n '1s/.*(.*-\\([^\\.]*\\)\\..*).*/\\1/p'
	`
#        abi_meta=`cd "$master_main/$repo2" && \
#                git cat-file -p "$branch2:meta-source/debian/changelog" | \
#		sed -n '1s/.*(.*\\.\\([^\\.]*\\)\\.[^\\.]*).*/\\1/p'
#	`

	prev2=`cat "$curr2" 2>/dev/null || echo 0`

	echo "repo2<$repo2> branch2<$branch2> abi_tip<$abi_tip> prev2<$prev2>"

	# If the meta abi number is behind then organise getting it updated.
	if [ "$prev2" -lt "$abi_tip" ]; then
		# Commit the new tip.
		echo "$abi_tip" >"$curr2.new"
		mv -f "$curr2.new" "$curr2"

		echo "$here/cod-enqueue" "A" \
			"$here/cod-source" "$ppa" "$repo2" "$series" \
				"$branch2" "$date" "$abi_tip"
		"$here/cod-enqueue" "A" \
			"$here/cod-source" "$ppa" "$repo2" "$series" \
				"$branch2" "$date" "$abi_tip"
	fi
done <<EOL
test-devel wily linux master-next linux-meta master -
pre-proposed vivid linux master-next linux-meta master no-release
pre-proposed utopic linux master-next linux-meta master no-release
pre-proposed trusty linux master-next linux-meta master no-release
pre-proposed precise linux master-next linux-meta master no-release
pre-proposed precise linux-lbm master no-release
pre-proposed precise linux lts-backport-trusty - - no-release
EOL
#pre-proposed lucid linux master-next linux-meta master no-release
#pre-proposed lucid linux-lbm master no-release
#pre-proposed utopic linux goldfish linux-meta goldfish -
#pre-proposed utopic linux grouper linux-meta grouper -
#pre-proposed utopic linux maguro linux-meta maguro -
#pre-proposed utopic linux mako linux-meta mako -
#pre-proposed utopic linux manta linux-meta manta -
#pre-proposed raring linux-lbm master no-release
#pre-proposed raring linux master-next linux-meta master no-release
