#!/bin/bash
P='cod-ubuntu-config'

if [ "$#" -ne 4 ]; then
	echo "Usage: $0 <series> <package> <version> <tag>" 1>&2
	exit 1
fi

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

. "$here/lib-build"
. "$here/lib-chroot"

series="$1"
package="$2"
version="$3"
tag="$4"

master_tree_select

# Ensure we have the commit identified.
repo_remote_update_list $series

# Clean out the rubbish.
rm -rf CONFIGS

# Pick a sensible release to build the configs in.
series_to_build_release "$series"
build_release="$RET"

# Make sure git is ready for anything...
rm -rf .git/rebase-apply
git reset --hard HEAD
git clean -x -f -d

# Make a branch at the specified commit.
git checkout HEAD^ --
git branch -D "config-$id" || true
git checkout -b "config-$id" "$tag"

# Generate the configs at this checkout.
do_chroot "$build_release-amd64" \
	fakeroot debian/rules clean genconfigs

# Output.
html="$HOME/public_html/config/$series/$package/$version"
mkdir -p "$html"

cp -p CONFIGS/* "$html"
