#!/usr/bin/python
from __future__ import print_function

import json
import os
import sys
from urllib import quote

directory = sys.argv[1]

results = []
for (dirname, dirs, files) in os.walk(directory):
    if 'latest.json' not in files:
        continue

    with open(os.path.join(dirname, 'latest.json')) as entry_fd:
        entry = json.load(entry_fd)

    results.append(entry)

results.sort(key=lambda x: x['series'] + ' ' + x['package'])

meta = {}

html = os.path.join(directory, "index.html.new")

with open(html, "w") as html_fd:
    print('''<html>
<head>
<title>Build Tests Summary</title>
<style>
.GOOD {{ background-color: green; }}
.FAIL {{ background-color: red; }}
.UBUNTU {{ background-color: #FFFF99; }}
table.matrix {{
    border-collapse: collapse;
}}
table.matrix th {{
    text-align: left;
    padding-left: 5px;
    padding-right: 5px;
}}
table.matrix td {{
    text-align: left;
    padding-left: 5px;
    padding-right: 5px;
}}
#table.matrix, table.matrix th, table.matrix td {{
#   border: 1px solid black;
#}}
#.row:nth-child(6n+1) {{ background-color: darkgrey }}
#.row:nth-child(6n+2) {{ background-color: darkgrey }}
#.row:nth-child(6n+3) {{ background-color: darkgrey }}
.row:nth-child(even) {{ background-color: lightgrey }}

</style>
</head>
<body>
<h1>Build Tests Summary</h1>
<table class="matrix">
<tr><th>Series<th>Package<th>Changeset<th>Builder<th>Status'''.format(**meta), file=html_fd)
    for entry in results:
        status = entry['status']

        row_class = 'row'
        #if entry['id'].startswith('Ubuntu-'):
        #    row_class = 'UBUNTU'

        if status == '0':
            status_string = 'GOOD'
            status_class = 'GOOD'
        else:
            status_string = 'FAIL rc=' + status
            status_class = 'FAIL'
        commit_url = "https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/{package}/+git/{series}/commit/?id={hash}".format(**entry)
        status_url = "http://kernel.ubuntu.com/~kernel-ppa/test-build/"
        status_url += quote("{series}/{package}/{directory}".format(**entry))
        print('<tr class="{row_class}"><td>{series}<td>{package}<td><a href="{commit_url}">{id}</a> -- {subject}<td>{host}<td class="{status_class}"><a href="{status_url}">{status_string}</a>'.format(
            commit_url=commit_url,
            status_string=status_string,
            status_class=status_class,
            status_url=status_url,
            row_class=row_class,
            **entry
            ), file=html_fd)
    print('''</table>
<body>
</html>''', file=html_fd)
