#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

locks="/run/lock/cod-status"

locker="$here/../sbin/lock-record"

PATH='/usr/sbin:/usr/bin:/sbin:/bin'

if [ "$1" = "" ]; then
	[ ! -f "$locks/logs-done" ] && exit 0
	"$locker" 480 "$locks/chroots"		"$0" chroots &
	"$locker" 240 "$locks/gkp-cleanup"	"$0" gkp-cleanup &

	exit 0
fi

tools='/usr3/ubuntu/kteam-tools'

dashboard_status="$here/../dashboard-status"

case "$1" in
chroots)
	"$tools/chroot-setup/make_all" >>~kernel/logs/root-chroots.log 2>&1 && \
		"$dashboard_status" "update-chroots" "Host: `hostname`" "Update Chroots" 25h 26h
	;;
gkp-cleanup)
	"$tools/git-build-kernel/gbk-cleanup" --timestamp >>~kernel/logs/root-gbk-cleanup.log 2>&1 && \
		"$dashboard_status" "gbk-cleanup" "Host: `hostname`" "git-build-kernel cleanup" 5h 9h
	;;
esac

exit 0
