#!/bin/bash
P="cod-broken"

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

tmp="/tmp/$P.$$"

"$here/cod-mainline-broken" >"$tmp"
[ -s "$tmp" ] && "$here/../ktl/announce.py" --body-file "$tmp" cod-mainline-broken "mainline-builds: published results broken"

"$here/cod-changeset-broken" >"$tmp"
[ -s "$tmp" ] && "$here/../ktl/announce.py" --body-file "$tmp" cod-changeset-broken "changeset: published results broken"

rm -f "$tmp"
