#!/bin/bash
P="cod-tags-trigger"

#set -e

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

commit="$1"

. "$here/lib-build"

master_tags="$master_state/upstream"
tags_list="$master_tags/TAGS"

# Ensure our master state exists.
mkdir -p "$master_tags"

# We are going to use the master linux build tree.
master_tree_select

# Pull in all trees containing tags we wish to build.
remotes="linus 2.6.32.y.33.z linux-stable extended-stable"
repo_remote_update_list $remotes

# Work out where we are going to push the tags et al to.
repo_remote_url "crack-push"; push_url="$RET"

# Keep the master branch in the crack repository up to date.
git push "$push_url" "linus/master:master"

#
# UPSTREAM TAGS: Find all the new upstream release tags.
#
git tag -l >"$tags_list.new"

diff "$tags_list" "$tags_list.new" | \
	awk '/>/ && $2 ~ /^v/ { print $2 }' | tac >"$tags_list.added"

# Commit the list.
mv "$tags_list.new" "$tags_list"

# Run the list.
while read commit
do
	# Note if this fails the job will fail, but it is better that the job
        # is created and logged so we can rerun it rather than never knowing
        # about it.
        git push "$push_url" tag "$commit"

	"$here/cod-enqueue" "mainline-build" "crack" "$commit"
done <"$tags_list.added"

rm -f "$tags_list.added"
