#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

locks="/run/lock/cod-status"

locker="$here/../sbin/lock-record"
if [ "$1" = "" ]; then
	"$locker"  15 "$locks/machine-check"		"$0" machine-check
	"$locker" 240 "$locks/kteam-tools"		"$0" kteam-tools
	"$locker"   5 "$locks/mainline-worker"		"$0" mainline-worker
	"$locker"  30 "$locks/mainline-failsafe"	"$0" mainline-worker-failsafe
	exit 0
fi

case "$1" in
machine-check)
	"$HOME/bin/dashboard-status" "machine-check" "Host: `hostname`" "Machine Check" 20m 30m
	;;
kernel-tools)
	(cd "$HOME/kteam-tools" && git pull >update.log 2>&1 && "$HOME/bin/dashboard-status" "machine-kteam-tools" "Host: `hostname`" "Update Tools" 60m 65m)
	;;
mainline-worker)
	[ ! -f "$locks/chroots-done" ] && exit 0
	[ ! -f "$locks/machine-check-done" ] && exit 0
	$HOME/kteam-tools/sbin/cron-start $HOME/kteam-tools/mainline-build/mainline-worker -- 'Mainline Builds' 'Mainline Worker' 30m 45m >>$HOME/logs/cod-worker.log 2>&1
	;;
mainline-worker-failsafe)
	$HOME/kteam-tools/mainline-build/mainline-worker-failsafe >>$HOME/logs/cod-worker.log 2>&1 && "$HOME/bin/dashboard-status" "mainline-builds-failsafe" "Mainline Builds" "Mainline Failsafe" 60m 65m
	;;
esac

exit 0
