#!/bin/bash
#
# cod-enqueue <tag> <cmd> ...
#
# Enqueue the specified command for execution by the crack-of-the-day
# builder.
#
P="cod-enqueue"

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

priority="$1"
cmd=`basename "$2"`
shift 2

exec $here/../queue/queue enqueue mainline "$priority" "$cmd" "$@"
#exec $here/mainline-work-kmsgq "$cmd" "$@"
