#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

cd "$here" || exit 1

if [ "$#" != 0 ]; then
	echo "Usage: $0" 1>&2
	exit 1
fi

echo "Starting `date`"
exec ./mainline-worker-kmsgq \
	--prefix-arg ./cod-queue-runner \
	--admin mainline-cleaner \
	--command cod-queue-publish \
	`hostname` mainline-queue
