#!/bin/bash
#
# cod-enqueue <tag> <cmd> ...
#
# Enqueue the specified command for execution by the crack-of-the-day
# builder.
#
P="cod-enqueue"

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

priority="A"

#exec $here/../queue/queue enqueue mainline "$priority" "$@"
echo `date --rfc-3339=seconds` $here/mainline-work-kmsgq "$@" >>"$HOME/logs/cod-enqueue-`date +\%Y-\%U`"
exec $here/mainline-work-kmsgq "$@"
