#!/bin/bash
P="cod-broken"

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

dir="public_html/status/broken"
mkdir -p "$dir"

check()
{
	local which="$1"
	local msg="$2"

	echo "$P: $which ..."

	# Generate the old/new combination.
	touch "$dir/$which"
	"$here/$which" >"$dir/$which.new"

	changes=$(diff -u "$dir/$which" "$dir/$which.new" | grep -c '^\+[^\+]')
	echo "$P: $which ... changes=$changes"
	if [ "$changes" -ne 0 ]; then
		"$here/../bin/announce" "$which" "$msg" "http://kernel.ubuntu.com/~kernel-ppa/status/broken/$which"
	fi

	# Commit this version.
	test -f "$dir/$which.old" && rm "$dir/$which.old"
	ln "$dir/$which" "$dir/$which.old"
	mv "$dir/$which.new" "$dir/$which"
}

check cod-mainline-broken "mainline-builds: published results broken"
check cod-changeset-broken "changeset: published results broken"
