#!/bin/bash
P="cod-crack-trigger"

#set -e

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

commit="$1"

. "$here/lib-build"

master_tags="$master_state/upstream"
tags_list="$master_tags/TAGS"

# Ensure our master state exists.
mkdir -p "$master_tags"

# We are going to use the master linux build tree.
master_tree_select

#
# UPSTREAM COD: builds of upstream tree tips
#
remotes="linus drm-2.6 drm-intel debloat-testing extended-stable"
repo_remote_update_list $remotes

date="`date +%F`"
while read branch abi base parent
do
	curr="$master_tags/$base"
	# Check for upstream crack of the day.
	tip=`git log --pretty=format:%H $branch^..$branch | head -1`
	prev=`cat "$curr" 2>/dev/null || true`

	pcurr="$master_tags/$parent"
	pprev=`cat "$pcurr" 2>/dev/null || true`

	echo "branch<$branch> tip<$tip> prev<$prev> pprev<$pprev>"

	if [ "$tip" = "" -o "$tip" = "$prev" ]; then
		continue
	fi

	# Commit the new tip.
	echo "$tip" >"$curr.new"
	mv -f "$curr.new" "$curr"

	# Check we are not also the same as any parental tip.  There
	# is no point in rebuilding if we are and generating two
	# identicle builds.  Note we have committed the tip already
	# so we can have cascaded parents.
	if [ "$tip" = "$pprev" ]; then
		continue
	fi

	"$here/cod-enqueue" "C" \
		"$here/mainline-build" "${remotes// /,}" "$tip" "$abi" "$base" "$date"
done <<EOL
linus/master					999	daily
drm-2.6/drm-next				996	drm-next
drm-intel/drm-intel-next			997	drm-intel-next
drm-intel/drm-intel-nightly			994	drm-intel-nightly
debloat-testing/master				993	debloat-testing
extended-stable/linux-3.5.y-review		992     linux-3.5.y.z-review
extended-stable/linux-3.5.y-queue		991     linux-3.5.y.z-queue	linux-3.5.y.z-review
extended-stable/linux-3.8.y-review		992     linux-3.8.y.z-review
extended-stable/linux-3.8.y-queue		991     linux-3.8.y.z-queue	linux-3.8.y.z-review
extended-stable/linux-3.11.y-review		992     linux-3.11.y.z-review
extended-stable/linux-3.11.y-queue		991     linux-3.11.y.z-queue	linux-3.11.y.z-review
EOL
# Also allocated
# 995: sconklin -- wayland
#
# NOTE: if you add a daily build above ensure it is recorded on the
# TopicBranches page, and also ensure you add it to the cleanup script.
