#!/bin/bash
P="mainline-trigger-daily"

#set -e

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

#
# MAINLINE CRACK: tips of various mainline trees.
#
"$here/cod-crack-trigger"

ofile="$HOME/public_html/status/mainline-daily.dashboard"
echo "Daily%sTrigger `date +%s` 87300 89100" >"$ofile.new"
mv -f "$ofile.new" "$ofile"

echo "$P: trigger run complete"
