#!/bin/bash
P='mainline-build'

if [ "$#" -ne 2 -a "$#" -ne 5 ]; then
	echo "Usage: $0 <remotes> <tag>" 1>&2
	echo "Usage: $0 <remotes> <commit> <abi> <out> <date>" 1>&2
	exit 1
fi

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

. "$here/lib-build"

remotes="$1"
commit="$2"
abi="$3"
base="$4"
date="$5"

if [ "$#" -eq 2 ]; then
	exec "$here/cod-mainline-core" "--priority" "3" -- "$remotes" "$commit" "mainline/$commit"
else
	exec "$here/cod-mainline-core" "--priority" "2" -- "$remotes" "$commit" "mainline/$base/$date"
fi
