#!/usr/bin/python3
from __future__ import print_function

import sys

from ktl.kernel_series import KernelSeries

def usage():
    print("""
Usage: mainline-config <mode>
       mode:
         lib-build      -- repository configuration for lib-build
          """.strip(), file=sys.stderr)
    sys.exit(1)

if len(sys.argv) != 2:
    usage()

mode = sys.argv[1]

kernel_series = KernelSeries()

if mode == 'lib-build':
    for series in sorted(kernel_series.series, key=KernelSeries.key_series_name):
        for source in sorted(series.sources, key=lambda x: x.name):
            for package in sorted(source.packages, key=lambda x: x.name):
                repo = package.repo
                if repo:
                    if source.name == 'linux' and package.name == source.name:
                        print("repo_remote_url_set '{}' '{}';".format(series.codename, repo.url))
                    print("repo_remote_url_set '{}--{}' '{}';".format(series.codename, package.name, repo.url))

else:
    usage()
