#!/usr/bin/python3
from __future__ import print_function

from ktl.kernel_series import KernelSeries

kernel_series = KernelSeries()

for series in sorted(kernel_series.series, key=KernelSeries.key_series_name):
    for source in sorted(series.sources, key=lambda x: x.name):
        for package in sorted(source.packages, key=lambda x: x.name):
            repo = package.repo
            if repo:
                if source.name == 'linux' and package.name == source.name:
                    print("repo_remote_url_set '{}' '{}';".format(series.codename, repo.url))
                print("repo_remote_url_set '{}--{}' '{}';".format(series.codename, package.name, repo.url))
