#!/bin/bash
P="mainline-trigger-daily"

set -e

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

#
# UBUNTU SOURCE: source package uploads, tips of the ubuntu trees etc
#
"$here/cod-source-trigger"

#
# MAINLINE CRACK: tips of herton's prestable branches.
#
"$here/cod-prestable-trigger"

#
# MAINLINE CRACK: tips of various mainline trees.
#
"$here/cod-crack-trigger"

echo "$P: trigger run complete"
