#!/bin/bash

if [ ! -f "COMMIT" ]; then
	echo "WARNING: no COMMIT: `pwd`"
	exit 1
fi

{
	read commit
	read sha1
} <"COMMIT"
[ "$sha1" = "" ] && sha1='unknown'

case "$commit" in
cod/tip/*)	repo="testing/crack.git" ;;
*rc[0-9]*)	repo="linux.git" ;;
*)		repo="linux-stable.git" ;;
esac

{
	echo "git://kernel.ubuntu.com/virgin/$repo $commit $sha1"
	for patch in ????-*
	do
		echo "$patch"
	done
} >"SOURCES"

{
    cat - <<EOL
These binary packages represent builds of Linus' kernel tree at the commit below:

    $commit ($sha1)

To obtain the source from which they are built fetch the commit below:

    git://kernel.ubuntu.com/virgin/$repo $commit

and apply the following patches on top in the order below:

EOL
    for patch in ????-*
    do
        echo "    $patch"
    done
    cat - <<EOL

This is summarised in the SOURCES file with these binaries.

For further information see: http://wiki.ubuntu.com/Kernel/MainlineBuilds
EOL
} >"README"
