#!/bin/bash
#
# mainline-worker-kmsgq-runner -- run the job and sync the results up.
#
P="mainline-worker-kmsgq-runner"

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

key="$HOME/.ssh/mainline-publish"

if [ ! -f "$key" ]; then
	echo "$P: $key: no queue key found ... run skipped"
	exit 1
fi

host=$( uname -n )
echo "$(date --rfc-3339=seconds) $P: starting job ($@) ..."
"$here/../ktl/announce.py" cod-job-start "cod-job $host starting $@" "Starting crack-of-the day job on $host:\n    $@\n"

"$@"

# If this produced any syncable results push them up.
results=0
for dir in "$HOME/public_html"/*
do
	[ "$dir" != "$HOME/public_html/*" ] && results=1
	break
done
if [ "$results" = 1 ]; then
	echo "$(date --rfc-3339=seconds) $P: syncing results to kernel.ubuntu.com ..."
	rsync -e "ssh -i $key" -a -v $HOME/public_html/* kernel-ppa@kernel.ubuntu.com:incoming/ && \
		rm -rf "$HOME/public_html/mainline" "$HOME/public_html/upload" "$HOME/public_html/config" "$HOME/public_html/native" "$HOME/public_html/test-build"
fi

"$here/../ktl/announce.py" cod-job-stop "cod-job $host finished $@" "Finished crack-of-the day job on $host:\n    $@\n"
echo "$(date --rfc-3339=seconds) $P: job complete"
