#!/bin/bash
#
# mainline-logrotate -- post logrotate trigger.
#
"$HOME/kteam-tools/mainline-build/mainline-work-kmsgq" --to admin-`uname -n` mainline-cleaner
"$HOME/kteam-tools/mainline-build/mainline-work-kmsgq" --to admin-`uname -n` quit
