#!/bin/bash
P="mainline-trigger-hourly"

#set -e

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

#
# MAINLINE TAGS: tagged versions in mainline trees.
#
"$here/cod-tags-trigger"

#
# STABLE QUEUE: coversion of the stable queue quilt trees
#
"$here/cod-stable-queue" "/srv/kernel.ubuntu.com/git/kernel-ppa/stable-queue-branches.git"

#
# UBUNTU SOURCE: source package uploads, tips of the ubuntu trees etc
#
"$here/cod-source-trigger"

ofile="$HOME/public_html/status/mainline-hourly.dashboard"
echo "Hourly%sTrigger `date +%s` 4500 6300" >"$ofile.new"
mv -f "$ofile.new" "$ofile"

echo "$P: trigger run complete"
