#!/bin/bash
P='mainline-cleaner'

if [ "$#" -ne 0 ]; then
	echo "Usage: $0" 1>&2
	exit 1
fi

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

. "$here/lib-build"

cd "$master_main" || exit 1
for tree in *
do
	[ ! -d "$tree/.git" ] && continue
	(
		echo "* Cleaning $tree ..."
		cd "$tree" || exit 1

		# Clean the tree hard.
		echo "** git cleaning repository ..."
		git clean -x -f -d

		echo "** git gc ..."
		git gc
	)
done

# Tidy up standard build mess.
rm -f "$master_main/"*.{deb,ddeb,udeb,buildinfo,changes,tar.gz}
