#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

cd "$here" || exit 1

echo "Starting `date`"
exec ./mainline-worker-kmsgq \
	--prefix-arg ./mainline-worker-kmsgq-runner \
	--admin mainline-cleaner \
	--command cod-source \
	--command cod-ubuntu-config \
	--command mainline-build \
	--command mainline-flush \
	--command cod-mainline-native-source \
	`hostname` mainline-todo \
	"$@"
