#!/bin/bash
P="mainline-trigger-daily"

set -e

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

#
# MAINLINE CRACK: tips of various mainline trees.
#
"$here/cod-crack-trigger"

echo "$P: trigger run complete"
