#!/bin/bash

state="$HOME/COD/.runner.state"

# If we have no job running, all is well.
if [ ! -f "$state" ]; then
	exit 0
fi

killit=''

# Check for the common failures which cause hangs.
if [ "$killit" = '' ]; then
	last_msg=$( tail -1 "$HOME/logs/cod-worker.log" )
	case "$last_msg" in
	'libfakeroot, when sending message: Interrupted system call')
		killit="libfakeroot hang"
		;;
	esac
fi

# Check for long periods of quiet indicative of a hang.
if [ "$killit" = '' ]; then
	now=$( date +%s )
	last_update=$( stat --format=%Z ~/logs/cod-worker.log )
	let minutes="($now - $last_update) / 60"

	if [ "$minutes" -ge 15 ]; then
		killit="log silent for more than 15 minutes"
	fi
fi

# Check for excessive run times.
if [ "$killit" = '' ]; then
	now=$( date +%s )
	read started <"$state"
	let hours="($now - $started) / 3600"

	# If it has been running less than 4 hours all is well.
	if [ "$hours" -ge 4 ]; then
		killit="running for more than 4 hours"
	fi
fi

# No reason to euthanise.
if [ "$killit" = '' ]; then
	exit 0
fi

echo "$0: killing current runner -- $killit"

mv "$state" "$state.killed"
kill $( lsof -t /tmp/mainline-worker.lck )

exit 0
