#!/bin/bash

if [ "$#" -ne 2 ]; then
	echo "Usage: $0 <log> <prefix>" 1>&2
	exit 1
fi
file="$1"
prefix="$2"

<"$file" \
awk -v prefix="$prefix" '
	BEGIN			{ what="" }
	/^-\+\+\+-.*\//		{ print "DODGY marker ignored"; next }
	/^-\+\+\+- begin /	{ print "BEGIN: " $3; what=prefix "." $3; next }
	/^-\+\+\+- end /	{ print "END: " $3; what=""; next }
	(what != "")		{ print >>what }
'
