#!/bin/bash
#
# mainline-logrotate -- post logrotate trigger.
#
if [ "$#" != 1 ]; then
	echo "Usage: $0 <queue>" 1>&2
	exit 1
fi
queue="$1"

to="$queue--$(uname -n)"

"$HOME/kteam-tools/mainline-build/mainline-work-kmsgq" --to "$to" mainline-cleaner
"$HOME/kteam-tools/mainline-build/mainline-work-kmsgq" --to "$to" quit
