#!/usr/bin/python
from __future__                         import print_function
import smtplib
import sys
import os
from ktl.announce                       import Announce

commit = sys.argv[1]
published = sys.argv[2]
reason = sys.argv[3]
built = sys.argv[4]

status = []
overall_status = 'succeeded'
with open(built) as bfd:
    for line in bfd:
        args = line.strip().split()
        if args[0] == 'Status:':
            if int(args[2]) != 0:
                overall_status = 'failed'
                state = 'failed'
            else:
                state = 'good'
            status.append('    ' + args[1] + ': ' + state + ' (rc=' + str(args[2]) + ')')

params = {
    'commit': commit,
    'published': published,
    'user': os.environ['USER'],
    'reason': reason,
    'overall_status': overall_status,
    'status': '\r\n'.join(status),
}
params['url'] = "http://kernel.ubuntu.com/~{user}/mainline/{published}".format(**params)
summary = "mainline build: {commit} {reason} complete {overall_status} at {url}/\n".format(**params)

# Add the From: and To: headers at the start!
subject = "Mainline Build {commit} {reason} {overall_status}".format(**params)
body  = """The mainline build ({reason}) for {commit} is now complete ({overall_status}) and available
at the URL below:\r
\r
    {url}/\r
\r
Build architecture status:\r
{status}\r
\r
See the CHANGES file for the list of changes from the previous version:\r
\r
    {url}/CHANGES\r
\r
Note that these builds do not contain any Ubuntu specific patches and\r
are not supported.\r
\r
Kernel Team\r
""".format(**params)

announce = Announce()
announce.send('cod-mainline-' + reason, subject=subject, body=body, summary=summary)
