#!/usr/bin/python3
from __future__ import print_function

import os
import sys

sys.path.append(os.path.realpath(
    os.path.join(os.path.dirname(__file__), os.pardir, "libs")))

from ktl.kernel_series import KernelSeries

def usage():
    print("""
Usage: kta-config <mode>
       mode:
         origs            -- orig tarball data
         repositories     -- repository URL list
          """.strip(), file=sys.stderr)
    sys.exit(1)

if len(sys.argv) != 2:
    usage()

mode = sys.argv[1]

kernel_series = KernelSeries()

if mode == 'origs':
    for series in sorted(kernel_series.series, key=KernelSeries.key_series_name):
        if not series.opening_ready('repositories'):
            continue
        for source in sorted(series.sources, key=lambda x: x.name):
            if source.versions:
                print("{supported} {version} {short}/{long}/{long}_{version}.orig.tar.gz".format(supported=source.supported, short=source.name[0], long=source.name, version=source.versions[-1]))

elif mode == 'repositories':
    url_seen = {}
    for series in sorted(kernel_series.series, key=KernelSeries.key_series_name):
        if series.opening_ready('repositories') is False:
            continue
        if series.esm:
            continue

        for source in sorted(series.sources, key=lambda x: x.name):
            if not source.supported:
                continue
            if source.name == 'linux':
                form = 'ubuntu-{series}{type}.git'
                variant = ''
            elif source.name.startswith('linux-'):
                form = 'ubuntu-{variant}-{series}{type}.git'
                variant = source.name.replace('linux-', '')
            for package in sorted(source.packages, key=lambda x: x.name):
                if package.repo is None:
                    continue
                url = package.repo.url
                if url in url_seen:
                    continue
                url_seen[url] = True

                type = '-' + package.type if package.type is not None else ''
                name = form.format(
                    series=series.codename,
                    variant=variant,
                    type=type,
                    )
                print("{series} {pacakge} {name} {url}".format(
                    series=series.codename,
                    pacakge=package.name,
                    name=name,
                    url=url,
                    ))
