#!/bin/bash


# MIRROR wani -> launchpad
while read repo url
do
    echo "*** $repo ..."
    (cd "/srv/kernel.ubuntu.com/git/$repo" && git push --mirror "$url")
done <<EOL
ubuntu/ubuntu-vivid.git               git+ssh://kernel-ppa@git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/vivid
ubuntu/ubuntu-vivid-meta.git          git+ssh://kernel-ppa@git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-meta/+git/vivid
ubuntu/ubuntu-vivid-signed.git        git+ssh://kernel-ppa@git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-signed/+git/vivid
ubuntu/ubuntu-utopic.git              git+ssh://kernel-ppa@git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/utopic
ubuntu/ubuntu-utopic-meta.git         git+ssh://kernel-ppa@git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-meta/+git/utopic
ubuntu/ubuntu-utopic-signed.git       git+ssh://kernel-ppa@git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-signed/+git/utopic
ubuntu/ubuntu-trusty.git              git+ssh://kernel-ppa@git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/trusty
ubuntu/ubuntu-trusty-meta.git         git+ssh://kernel-ppa@git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-meta/+git/trusty
ubuntu/ubuntu-trusty-signed.git       git+ssh://kernel-ppa@git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-signed/+git/trusty
ubuntu/ubuntu-precise.git             git+ssh://kernel-ppa@git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/precise
ubuntu/ubuntu-precise-meta.git        git+ssh://kernel-ppa@git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-meta/+git/precise
ubuntu/ubuntu-precise-signed.git      git+ssh://kernel-ppa@git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-signed/+git/precise
ubuntu/ubuntu-precise-lbm.git         git+ssh://kernel-ppa@git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-backports-modules-3.2.0/+git/precise
virgin/testing/crack.git              git+ssh://kernel-ppa@git.launchpad.net/~ubuntu-kernel-test/ubuntu/+source/linux/+git/mainline-crack
virgin/testing/drm-intel.git          git+ssh://kernel-ppa@git.launchpad.net/~ubuntu-kernel-test/ubuntu/+source/linux/+git/mirror-drm-intel
EOL

# MIRROR launchpad -> wani
while read repo url
do
    echo "*** $repo ..."
    if [ ! -d "/srv/kernel.ubuntu.com/git/$repo" ]; then
	(cd "/srv/kernel.ubuntu.com/git" && mkdir "$repo" && git init --bare "$repo")
    fi
    (cd "/srv/kernel.ubuntu.com/git/$repo" && \
        git fetch "$url" '+refs/heads/*:refs/heads/*' '+refs/tags/*:refs/tags/*')
done <<EOL
kernel-ppa/mirror/ubuntu-wily.git          git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/wily
kernel-ppa/mirror/ubuntu-wily-meta.git     git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-meta/+git/wily
kernel-ppa/mirror/ubuntu-wily-signed.git   git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-signed/+git/wily
kernel-ppa/mirror/ubuntu-xenial.git        git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/xenial
kernel-ppa/mirror/ubuntu-xenial-meta.git   git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-meta/+git/xenial
kernel-ppa/mirror/ubuntu-xenial-signed.git git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux-signed/+git/xenial
kernel-ppa/mirror/unstable.git             git://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/unstable
EOL

date
