#!/bin/bash

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

# Flags
first=false
[ "$1" = "first" ] && first=true

# MIRROR wani -> launchpad
while read url alt_url master flags
do
    case ",$flags," in
    *,inactive,*)	continue ;;
    esac
    case "$master" in
    wani) 		;;
    *)			continue ;;
    esac
    case "$alt_url" in
    -)			continue ;;
    esac

    echo "*** $url -> $alt_url ..."
    repo=$( echo "$url" | sed -e 's@git://kernel.ubuntu.com/@/srv/kernel.ubuntu.com/git/@' )
    alt_url=$( echo "$alt_url" | sed -e 's_git://git.launchpad.net/_git+ssh://kernel-ppa@git.launchpad.net/_' )

    (cd "$repo" && git push --mirror "$alt_url")
done <"$here/../info/repositories.txt"

# MIRROR launchpad -> wani
while read url alt_url master flags
do
    case ",$flags," in
    *,inactive,*)	continue ;;
    esac
    case "$master" in
    launchpad) 		;;
    *)			continue ;;
    esac
    case "$alt_url" in
    -)			continue ;;
    esac

    echo "*** $alt_url -> $url ..."
    repo=$( echo "$url" | sed -e 's@git://kernel.ubuntu.com/ubuntu/@/srv/kernel.ubuntu.com/git/kernel-ppa/mirror/@' )

    if [ ! -d "$repo" ]; then
	(
		mkdir "$repo" || exit 1
		git init --bare "$repo"
		cp "$repo/hooks/post-update.sample" "$repo/hooks/post-update"
	)
    fi
    (cd "$repo" && \
        git fetch "$alt_url" '+refs/heads/*:refs/heads/*' '+refs/tags/*:refs/tags/*')
done <"$here/../info/repositories.txt"

date
