#!/usr/bin/python
from __future__ import print_function

import os
import sys

sys.path.append(os.path.realpath(
    os.path.join(os.path.dirname(__file__), os.pardir, "libs")))

from ktl.kernel_series import KernelSeries

kernel_series = KernelSeries()

# Commands: primary
cmd = sys.argv[1]

url_seen = {}
if cmd == 'repositories':
    for series in sorted(kernel_series.series, key=KernelSeries.key_series_name):
        if series.opening_ready('repositories') is False:
            continue
        if series.esm:
            continue

        for source in sorted(series.sources, key=lambda x: x.name):
            if not source.supported:
                continue
            if source.name == 'linux':
                form = 'ubuntu-{series}{type}.git'
                variant = ''
            elif source.name.startswith('linux-'):
                form = 'ubuntu-{variant}-{series}{type}.git'
                variant = source.name.replace('linux-', '')
            for package in source.packages:
                if package.repo is None:
                    continue
                url = package.repo.url
                if url in url_seen:
                    continue
                url_seen[url] = True

                type = '-' + package.type if package.type is not None else ''
                name = form.format(
                    series=series.codename,
                    variant=variant,
                    type=type,
                    )
                print("{series} {pacakge} {name} {url}".format(
                    series=series.codename,
                    pacakge=package.name,
                    name=name,
                    url=url,
                    ))
