#!/usr/bin/python

import json
import sys

import yaml

data = yaml.safe_load(sys.stdin.read())

def yaml_to_json(obj):
    if hasattr(obj, 'isoformat'):
        return obj.isoformat()
    else:
        raise TypeError, 'Object of type %s with value of %s is not JSON serializable' % (type(obj), repr(obj))

print(json.dumps(data, default=yaml_to_json))
