#!/bin/bash

if [ "$#" -eq 0 ]; then
	set - web
fi
out="$1"
payload="$1/kernel-stable-dashboard.html"

./gather-releases > supported-releases.json
./gather-releases --all > all-releases.json
./generate-dashboard kernel-stable-dashboard.rc >"$payload.tmp" && mv "$payload.tmp" "$payload"

if [ ! -f "$out/kernel-stable-board.html" ]; then
	echo LINKING BOARD
	ln -sf $(realpath --relative-to="$out" web/kernel-stable-board.html) "$out"
fi
if [ ! -d "$out/media" ]; then
	echo LINKING MEDIA
	ln -sf $(realpath --relative-to="$out" web/media) "$out"
fi
