#!/usr/bin/env python3
import yaml
import argparse
import os
import re
from datetime   import datetime, timedelta

# the so-trello root dir needs to be on PYTHONPATH
from trellotool.trellotool              import TrelloTool
from ktl.kernel_series                  import KernelSeries
from ktl.utils                          import run_command

class TrelloError(Exception):
    pass


class UpstreamBoard:
    def __init__(self, tt, name, dryrun=False):
        """
        :param tt: TrelloTool object
        :param name: name of the board
        """
        self.dryrun = dryrun
        self.tt = tt
        self.name = name
        self.id = None
        self.url = None
        self.default_list_name = None
        self.lists = {}

    def create(self, org):
        """
        Create the Trello board

        :param org: Trello organization (team)
        :return None
        """
        params = {
            'name': self.name,
            'idOrganization': org,
            'prefs_permissionLevel': 'org',
            'defaultLists': 'false'
        }

        if self.dryrun:
            print('DRY: Create board: "{}"'.format(self.name))
        else:
            print('Create board: "{}"'.format(self.name))
            self.tt.trello.board_create(**params)
        self.lookup_board_id()

    def lookup_board_id(self):
        if self.dryrun:
            self.id = 0
            self.url = 'http://this.is.a.dryrun.info'
            return

        for board in self.tt.trello.member_boards('me'):
            if board['name'] == self.name:
                self.id = board['id']
                self.url = board['url']
                return
        raise TrelloError("Could not find id for board '%s'" % self.name)

    def add_lists(self, list_names, default_list):
        """
        Add the lists to the board and save the default list
        to be used to later add the cards to

        :param list_names: list with the list names
        :param default_list: default list to add the cards to
        :return: None
        """
        self.default_list_name = default_list
        if self.dryrun:
            list_id = 1
            for list_name in list_names:
                isdefault = ''
                if list_name == default_list:
                    isdefault = '*'
                print('DRY: Add list: {}{}'.format(list_name, isdefault))
                self.lists[list_name] = list_id
                list_id += 1
            return

        for list_name in list_names:
            params = {
                'name': list_name,
                'pos': 'bottom'
            }
            self.tt.trello.board_addlist(self.id, **params)

        for board_list in self.tt.trello.board_lists(self.id):
            self.lists[board_list['name']] = board_list['id']

    def add_card(self, name, desc=None, list_name=None):
        """
        Add the given card to the default list board

        :param name: card name
        :param desc: card description
        :param list_name: optional alternative list target
        :return: None
        """
        if list_name is not None:
            if list_name not in self.lists:
                raise TrelloError("Undefined list target for '{}'({})".format(name, list_name))
        else:
            list_name = self.default_list_name
        list_id = self.lists[list_name]

        params = {
            'name': name,
            'pos': 'bottom',
        }
        if desc:
            params['desc'] = desc

        if self.dryrun:
            print('DRY: Add "{}" card to "{}"'.format(name, list_name))
            if desc:
                print('DRY:     "{}"'.format(desc))
        else:
            print('Adding card: {}'.format(name))
            self.tt.trello.list_addcard(list_id, **params)

    def add_member(self, member_id, member_type):
        """
        Add a given member ID as the specified type to the board

        :param member_id: member ID
        :param member_type: member type ('admin', 'normal', 'observer')
        :return: None
        """
        params = {
            'idMember': member_id,
            'type': member_type,
        }
        if self.dryrun:
            print('DRY: Add member: {} as {}'.format(member_id, member_type))
        else:
            if member_type == 'admin':
                print('Adding {} as an administrator'.format(member_id))
            else:
                print('Adding {} as normal user'.format(member_id))
            self.tt.trello.board_addmember(self.id, **params)


class DevelCardsCreator:
    def __init__(self, args):
        """
        :param args: argparse args object
        """

        self.args = args
        self.version = args.version
        self.config_file = args.config
        self.config = {}
        self.config_load()

        self.tt = TrelloTool()
        self.tt.assert_authenticated()

    def config_load(self):
        with open(self.config_file, 'r') as cfd:
            self.config = yaml.safe_load(cfd)

    def create(self):
        """
        Create the board, the lists and the cards and add the initial members
        of the board, taking the info from the config file

        :return: None
        """
        # create the board with the lists on the organization
        board_title = self.config['board']['prefix_name'] + self.version
        board = UpstreamBoard(self.tt, board_title, dryrun=self.args.dry_run)
        board.create(self.config['board']['trello_organization'])
        board.add_lists(self.config['board']['lists'], self.config['board']['default_list'])

        # Add the initial members of the board
        for member_id in self.config['board'].get('admin_members'):
            board.add_member(member_id, 'admin')
        for member_id in self.config['board'].get('normal_members'):
            board.add_member(member_id, 'normal')

        # add the cards to the board, under the default list
        for card in self.config['cards']:
            card_desc = None
            if 'description' in card:
                # Fields in the yaml file get encoded with escapes when it's loaded.
                # Un-escape the card description so they have the desired formatting.
                card_desc = card['description'].encode().decode('unicode_escape')

            card_list = None
            if 'list' in card:
                card_list = card['list']

            board.add_card(card['name'], card_desc, card_list)

        if self.args.dry_run:
            print("This was a dry-run - board was NOT created")
        else:
            print("Board '%s' created: %s" % (board.name, board.url))


if __name__ == '__main__':
    retval = 0
    default_config = '%s/create-upstream-board.yaml' % os.path.dirname(__file__)
    description = 'Create a Trello board with cards for upstream kernel'
    epilog = '''
The script reads the configuration from a yaml file yaml and creates a new
Trello board, adding the initial cards and members.

Examples:
    Run with the default options:
    $ create-upstream-board 5.7

    Do not create anything, just print what would be done:
    $ create-upstream-board --dry-run 5.7
'''.format(default_config)
    parser = argparse.ArgumentParser(description=description, epilog=epilog,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('version', metavar='VERSION', help='upstream kernel version',
                        action='store')
    parser.add_argument('--config', metavar='CONFIG',
                        help='config yaml file (default: {0})'.format(default_config),
                        required=False, action='store', default=default_config)
    parser.add_argument('--dry-run', help='only print steps, no action done', required=False,
                        action='store_true', default=False)
    args = parser.parse_args()

    # Check upstream version number, and remove leading 'v' if present
    match = re.fullmatch('v?([0-9]+\.[0-9]+)', args.version)
    if match is None:
        print('Error: Invalid version {}'.format(args.version))
        exit(1)
    args.version = match.group(1)

    try:
        DevelCardsCreator(args).create()
    except TrelloError as e:
        retval = 1
        print('Error: {}'.format(e))

    exit(retval)
