#!/bin/bash
#
# devel-config-summary -- generate a configuration settings summary for UDS
#
P="$0"

here=`dirname $0`
case "$here" in
/*) ;;
*)  here="`pwd`/$here" ;;
esac

format="wiki"
case "$1" in
--html)		format="html"; shift ;;
esac

if [ "$#" -ne 3 ]; then
	echo "Usage: $P <current series> <next series> <prefix>" 1>&2
	exit 1
fi
current="$1"
next="$2"
prefix="$3"

there_current="$current"
case "$there_current" in
/*) ;;
*)  there_current="`pwd`/$there_current" ;;
esac

there_next="$next"
case "$there_next" in
/*) ;;
*)  there_next="`pwd`/$there_next" ;;
esac

echo "*** $current ..."
"$here/lib-config/devel-config-info" "$there_current/debian.master/config/annotations" "$current"
echo "*** $next ..."
"$here/lib-config/devel-config-info" "$there_next/debian.master/config/annotations" "$next"

(
	cd "$next" || exit 1

	fakeroot debian/rules genconfigs >/dev/null 2>&1
	fakeroot debian/rules genportsconfigs >/dev/null 2>&1

	rm -f CONFIGS/ppc64-* CONFIGS/*highbank*
)

"$here/devel-config-summary-report" "$format" "$current" "$next" "$prefix"
