#!/bin/bash

here=$(dirname $(readlink -f "$0"))

builder="$here/ancillary-builder"
#builder="$here/ancillary-lookup"

if [ "$#" -eq 0 ]; then
	set - '--regular'
fi
if [ "$1" = "all" ]; then
	set - '--regular' '--security' '--lrm-spinner'
fi

echo "II: $@ ..."
"$here/ancillary-config" "$@" | \
while read public private
do
	echo "$public" "$private"
	"$builder" "$public" "$private"
done
