#!/bin/bash

here=$(dirname $(readlink -f "$0"))

builder="$here/lrm-ancillary-builder"
#builder="$here/lrm-ancillary-lookup"

if [ "$#" -eq 0 ]; then
	set - 'regular'
fi
if [ "$1" = "all" ]; then
	set - 'regular' 'security'
fi

for which in "$@"
do
	echo "II: $which ..."
	case "$which" in
	security)
		"$builder" ppa:canonical-kernel-security-team/ubuntu/ppa    ppa:canonical-kernel-security-team/ubuntu/ppa
		"$builder" ppa:canonical-kernel-security-team/ubuntu/ppa2   ppa:canonical-kernel-security-team/ubuntu/ppa2
		"$builder" ppa:canonical-kernel-security-team/ubuntu/ppa3   ppa:canonical-kernel-security-team/ubuntu/ppa3
		"$builder" ppa:canonical-kernel-security-team/ubuntu/devel  ppa:canonical-kernel-security-team/ubuntu/devel
		"$builder" ppa:canonical-kernel-security-team/ubuntu/devel2 ppa:canonical-kernel-security-team/ubuntu/devel2
		"$builder" ppa:canonical-kernel-security-team/ubuntu/devel3 ppa:canonical-kernel-security-team/ubuntu/devel3
		"$builder" ppa:canonical-kernel-security-team/ubuntu/nv-dgx  ppa:canonical-kernel-security-team/ubuntu/nv-dgx
		"$builder" ppa:canonical-kernel-security-team/ubuntu/nv-dgx2 ppa:canonical-kernel-security-team/ubuntu/nv-dgx2
		"$builder" ppa:canonical-kernel-security-team/ubuntu/nv-dgx3 ppa:canonical-kernel-security-team/ubuntu/nv-dgx3
	;;
	regular)
		"$builder" ppa:canonical-kernel-team/ubuntu/ppa       ppa:canonical-kernel-team/ubuntu/ppa-ps
		"$builder" ppa:canonical-kernel-team/ubuntu/ppa2      ppa:canonical-kernel-team/ubuntu/ppa2-ps
		"$builder" ppa:canonical-kernel-team/ubuntu/bootstrap ppa:canonical-kernel-team/ubuntu/bootstrap-ps
		"$builder" ppa:canonical-kernel-team/ubuntu/unstable  ppa:canonical-kernel-team/ubuntu/unstable-ps
		"$builder" ppa:canonical-kernel-team/ubuntu/azure     ppa:canonical-kernel-team/ubuntu/azure-ps
		"$builder" ppa:fips-cc-stig/ubuntu/fips-build         ppa:fips-cc-stig/ubuntu/fips-build
		"$builder" ppa:canonical-kernel-dgx/ubuntu/build      ppa:canonical-kernel-dgx/ubuntu/build-ps
	;;
	esac
done
