#!/usr/bin/python3
from __future__ import print_function

import json
import os
import sys

from launchpadlib.launchpad import Launchpad

cred_file = os.path.join(".config", "credentials-ancillary-bot")
if not os.path.exists(cred_file):
    cred_file = None
lp = Launchpad.login_with('lrm-ancillary-builder', 'production', version='devel',
    credentials_file=cred_file)

# Work around a redirect handling issue in python3-lazr.restfulclient
# which fails when trying to carry over non-GET requests.  Look up
# my name (via +me), and then manually resolve that name to a user.
me_name = lp.me.name
me = lp.people[me_name]

primary_ref, adjunct_ref = sys.argv[1:]

primary = lp.archives.getByReference(reference=primary_ref)
#public = lp.archives.getByReference(reference='ppa:apw/ubuntu/private')
#print(primary)
# XXX: public + '-ps'
adjunct = lp.archives.getByReference(reference=adjunct_ref)
#print(adjunct)

# For private PPAs we will have to use the users subscription
# to form the URLs to download the components.  Lookup up any
# such subscription if needed.
subscription = None
if primary.private:
    subscription = me.getArchiveSubscriptionURL(archive=primary)
    if subscription is None:
        raise ValueError("no private subscription")

lrms = []
lrms += list(primary.getPublishedSources(source_name='linux-restricted-modules', status='Published'))
#lrms += list(primary.getPublishedSources(source_name='linux-restricted-modules', status='Pending'))
for lrm in lrms:
    #print(lrm)
    lrm_id = os.path.basename(lrm.self_link)
    lrg_name = lrm.source_package_name.replace('linux-restricted-modules', 'linux-restricted-generate')
    lrg_version = lrm.source_package_version
    #print(" ", lrg_name, lrg_version)
    lrgs = adjunct.getPublishedSources(exact_match=True, source_name=lrg_name, version=lrg_version)
    if len(lrgs) == 0:
        urls = []
        for url in lrm.sourceFileUrls():
            if subscription:
                deb = os.path.basename(url)
                package = deb.split('_')[0]
                prefix = package[0]
                url = os.path.join(subscription, 'pool', 'main', prefix, package, deb)
            urls.append(url)
        print(lrm_id, lrm.source_package_name, ' '.join(urls))

    else:
        print(lrm_id, lrm.source_package_name, '-')
