#!/usr/bin/env python3
#
# Perform checks on source packages and generate diffs for review
#

import argparse
import logging
import subprocess
import os
import sys
import signal
from glob import glob
import tempfile
import re

# Add ../libs to the Python search path
sys.path.append(os.path.realpath(os.path.join(os.path.dirname(__file__), os.pardir, 'libs')))

from ktl.log import cerror, cnotice

def dpkg_compare_versions(v1, op, v2):
    cmd = ["dpkg", "--compare-versions", v1, op, v2]
    ret = subprocess.run(cmd)
    return ret.returncode == 0

def dpkg_extract(dsc_path, dest_path):
    cmd = ["dpkg-source", "-x", dsc_path, dest_path]
    sp = subprocess.Popen(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
    stderr = sp.communicate()[1].decode()
    return (sp.returncode, stderr)

def normalize_control_file(path, ver, abi, upload):
    if not os.path.exists(path):
        return

    verabi = ver + '-' + abi
    fullver = verabi + '.' + upload

    with open(path, "r") as cfile:
        cfile_data = cfile.read()
    cfile_data = cfile_data.replace(fullver, "FULLVER")
    cfile_data = cfile_data.replace(verabi, "VERABI")
    cfile_data = cfile_data.replace(ver, "VERSION")
    with open(path, "w") as cfile:
        cfile.write(cfile_data)

def normalize_unsorted_file(path):
    with open(path, "r") as ufile:
        ufile_data = ufile.readlines()
    ufile_data.sort()
    with open(path, "w") as ufile:
        ufile.write(''.join(ufile_data))

def normalize_tree(path, ver, abi, upload):
    normalize_control_file(os.path.join(path, "debian", "control"), ver, abi, upload)
    for control_file in (
            glob("{}/debian/control.stub".format(path)) +
            glob("{}/debian.*/control.stub".format(path)) +
            glob("{}/debian/d-i/kernel-versions".format(path)) +
            glob("{}/debian.*/d-i/kernel-versions".format(path))
        ):
        normalize_control_file(control_file, ver, abi, upload)
    for unsorted_file in (
            glob("{}/debian.*/abi/*/*/*.modules".format(path)) +
            glob("{}/debian.*/abi/*/fwinfo".format(path))
        ):
        normalize_unsorted_file(unsorted_file)

def dsc_source_version(dsc_file):
    basename = os.path.basename(dsc_file)
    basename = os.path.splitext(basename)[0]
    return basename.split('_')[0:2]

def review_dscs(prev_dsc_file, dsc_file, output=None):
    (prev_source_pkg, prev_version) = dsc_source_version(prev_dsc_file)
    (source_pkg, version) = dsc_source_version(dsc_file)

    # Matches a kernel version string in the format of
    # VERSION-ABI.UPLOAD. The string 4.15.0-34.37 would match as
    # follows:
    #
    #  VERSION = 4.15.0
    #  ABI = 34
    #  UPLOAD = 37
    verabi_re = re.compile("([0-9]+\.[0-9]+\.0)[-.]([0-9]+)\.(.+)")

    m = verabi_re.match(version)
    (ver, abi, upload) = m.group(1, 2, 3)

    m = verabi_re.match(prev_version)
    (prev_ver, prev_abi, prev_upload) = m.group(1, 2, 3)

    if output:
        diff_path = output
    else:
        diff_dir = os.path.dirname(os.path.realpath(dsc_file))
        diff_path = os.path.join(diff_dir, "%s_%s.debdiff" % (source_pkg, version))

    cnotice("Generating %s" % diff_path)

    with tempfile.TemporaryDirectory() as tmpdir, open(diff_path, "w") as outfile:
        prev_dir = source_pkg + '_' + prev_version
        new_dir = source_pkg + '_' + version
        prev_path = os.path.join(tmpdir, prev_dir)
        new_path = os.path.join(tmpdir, new_dir)

        (ret, stderr) = dpkg_extract(prev_dsc_file, prev_path)
        if ret != 0:
            cerror("Failed to extract %s." % prev_dsc_file)
            cerror("Output from dpkg-source:")
            print(stderr, end='')
            sys.exit(1)
        normalize_tree(prev_path, prev_ver, prev_abi, prev_upload)

        (ret, stderr) = dpkg_extract(dsc_file, new_path)
        if ret != 0:
            cerror("Failed to extract %s." % dsc_file)
            cerror("Output from dpkg-source:")
            print(stderr, end='')
            sys.exit(1)
        normalize_tree(new_path, ver, abi, upload)

        cmd = ["git", "diff", "--no-index", "--no-prefix", "--stat", "-p",  prev_dir, new_dir]
        sp = subprocess.Popen(cmd, stdout=outfile, stderr=subprocess.PIPE, cwd=tmpdir)
        stderr = sp.communicate()[1].decode()
        if sp.returncode != 0 and sp.returncode != 1:
            cerror("Failed to diff trees. Output from 'git diff':")
            print(stderr, end='')
            sys.exit(1)

def review(prev_dsc_dir='', changes_files=[], output=None):
    prev_dscs = glob("%s/*.dsc" % prev_dsc_dir)

    count = 0
    for changes_file in changes_files:
        count += 1
        if not os.path.exists(changes_file):
            cerror("%s does not exist" % changes_file)
            sys.exit(1)

        (source_pkg, version) = dsc_source_version(changes_file)

        (prev_dsc_file, prev_version) = (None, None)
        for dsc_file in prev_dscs:
            (dsc_source, dsc_version) = dsc_source_version(dsc_file)

            # Don't consider files for other source packages ...
            if dsc_source != source_pkg:
                continue
            # ... or files with the same or a newer version
            if dpkg_compare_versions(version, "le", dsc_version):
                continue

            if not prev_version or dpkg_compare_versions(dsc_version, "gt", prev_version):
                (prev_dsc_file, prev_version) = (dsc_file, dsc_version)

        if not prev_dsc_file:
            cerror("Previous dsc file not found for %s" % changes_file)
            sys.exit(1)

        cmd = ["dcmd", "--dsc", changes_file]
        dsc_file = subprocess.check_output(cmd).decode().strip()

        if output:
            output_i = output.format(count=count, N='-' + count if count > 1 else '')
        else:
            output_i = None
        review_dscs(prev_dsc_file, dsc_file, output=output_i)

if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    desc = """
Run final checks on a source package set, and generate a set of diffs from the
previous package versions for review.
"""

    epilog = """
Examples:
  $ cranky review *.changes
      Run final checks against the specified .changes files. Debdiffs will be
      generated in the current directory for reviewing changes made since the
      previous package version. The source packages for previous package
      versions are expected to be in the current directory.

  $ cranky review --prev-dsc-dir=/path/to/prev *.changes
      Same as the above, but looks for previous source package versions in the
      specified path.
"""

    parser = argparse.ArgumentParser(description=desc, formatter_class=
                                     argparse.RawDescriptionHelpFormatter,
                                     epilog=epilog)
    parser.add_argument("changes_files", nargs="+",
                        help=".changes files for the package set")
    parser.add_argument("-p", "--prev-dsc-dir", default=".",
                        help="Path to previous source packages")
    parser.add_argument("-o", "--output", default=None,
                        help="Control the output filename")
    args = parser.parse_args()
    if (len(args.changes_files) == 2 and
        args.changes_files[0].endswith(".dsc") and
        args.changes_files[1].endswith(".dsc")
        ):
        review_dscs(args.changes_files[0], args.changes_files[1], args.output)
    else:
        review(**vars(args))
