#!/bin/bash
#
# cranky-fix -- identify the current repository and attempt to apply fixes to
#               it against the primary copies of repositories.
#

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <master directory>" 1>&2
	exit 1
fi
master="$1"

here=$(dirname "$0")
case "$here" in
/*) ;;
*)  here="$(pwd)/$here" ;;
esac

# identify the current tree type.
source=$(dpkg-parsechangelog -SSource)
type=""
debian=""
if [ "$type" = "" ]; then
	case "$source" in
	*-signed*)			type="signed" ;;
	*-meta*)			type="meta" ;;
	*-restricted-modules*)		type="lrm" ;;
	esac
fi
if [ "$type" = "" ]; then
	if [ -f "debian/debian.env" ]; then
		type="main"
		debian=$(awk -F= '($1 == "DEBIAN") { print $2 }' <debian/debian.env) 
	fi
fi
if [ "$type" = "" ]; then
	echo "$0: unable to identify repository type -- assuming other" 1>&2
	type='other'
fi

# identify the current series
series=$( LC_ALL=C dpkg-parsechangelog -SDistribution )
if [ "$series" = "UNRELEASED" ]; then
	series=$( LC_ALL=C dpkg-parsechangelog -c1 -SDistribution )
fi

bug="1786013"
FIX_VERBOSE="1" \
FIX_BUG="$bug" \
FIX_BUGLINK="BugLink: http://bugs.launchpad.net/bugs/$bug" \
FIX_MASTER="$master" \
FIX_DEBIAN="$debian" \
FIX_TYPE="$type" \
FIX_SERIES="$series" \
FIX_SOURCE="$source" \
	run-parts --regex '\.fix$' --exit-on-error --verbose "$here/fixes.d"
