#!/bin/bash

here=$(dirname "$(realpath -e "${0}")")

if [ "$#" -lt 1 ]; then
	echo "Usage: $0 <cmd> ..." 1>&2
	exit 1
fi
cmd="$1"
shift

if [ ! -f "$here/cranky-$cmd" ]; then
	echo "$0: $cmd: command unknown" 1>&2
	exit 1
fi

C="$0" P="cranky $cmd" exec "$here/cranky-$cmd" "$@"
