#!/usr/bin/env python3
#
# cranky-rmadison: An rmadison-like script for querying the Ubuntu archives
#                  and private PPAs.
#
# Copyright (C) 2018, Canonical Ltd.
#
# This script is distributed under the terms and conditions of the GNU General
# Public License, Version 3 or later. See http://www.gnu.org/copyleft/gpl.html
# for details.

import argparse
import logging
import os
import sys

from launchpadlib.launchpad import Launchpad

# Add ../libs to the Python search path
sys.path.append(os.path.realpath(os.path.join(os.path.dirname(__file__),
                                              os.pardir, 'libs')))

from crl.handle import Handle, HandleError
from ktl.log import cerror


def pocket_order(val):
    """
    Return a sort order number based on the pocket name
    """
    if "-proposed" in val[2]:
        return 3
    if "-updates" in val[2]:
        return 2
    if "-security" in val[2]:
        return 1
    return 0


def rmadison_lp(handle_set, show_all=False):
    """
    Query Launchpad for source package information
    """
    series = handle_set.series.codename
    routing = handle_set.source.routing
    packages = [package.name for package in handle_set.source.packages]

    # Temporarily disable logging of level INFO to silence launchpadlib and
    # then reenable logging again
    logging.disable(logging.INFO)
    lp = Launchpad.login_with("cranky", "production", version="devel")
    logging.disable(logging.NOTSET)

    lp_series = lp.distributions["ubuntu"].getSeries(name_or_version=series)

    result = []
    for package in sorted(packages):
        tmp = []
        for route in routing:
            dest = route[0]
            ppa, pocket = route[1][0]

            if dest == "build" or dest.endswith("-build"):
                # This is a builder PPA, not a publishing PPA, so skip it
                continue

            if ((dest not in ("release", "security", "updates", "proposed") and
                 not show_all)):
                # This is a non-standard PPA and we didn't ask for it, so skip it
                continue

            lp_archive = lp.archives.getByReference(reference=ppa)
            lp_sources = lp_archive.getPublishedSources(source_name=package,
                                                        distro_series=lp_series,
                                                        pocket=pocket,
                                                        exact_match=True,
                                                        order_by_date=True,
                                                        status="Published")
            if not lp_sources:
                # Nothing found in this PPA/pocket
                continue

            if dest == "release":
                pocket_name = series
            elif dest in ("security", "updates", "proposed"):
                pocket_name = "%s-%s" % (series, dest)
            else:
                pocket_name = "%s (ppa:%s)" % (series, dest)

            package_version = lp_sources[0].source_package_version
            package_date = lp_sources[0].date_published.strftime("%Y-%m-%d %H:%M")
            tmp.append([package, package_version, pocket_name, "source",
                        package_date])

        # Sort the temporary list by pocket names and add it to the result
        result.extend(sorted(tmp, key=pocket_order))

    return result


def print_table(data, show_ext=False):
    """
    Print the package list
    """
    # Add a header if we show extended info, otherwise truncate the table to
    # the first 4 columns
    if show_ext:
        data.insert(0, ["Name", "Version", "Pocket/PPA", "Type",
                        "Date Published"])
    else:
        data = [d[0:4] for d in data]

    # Determine the max width of each column
    widths = [len(max(col, key=len)) for col in zip(*data)]

    # Insert a header separator
    if show_ext:
        data.insert(1, ["-" * w for w in widths])

    # Print the formatted data
    for row in data:
        print('|'.join((" {:%d} " % w).format(r) for w, r in zip(widths, row)))


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    desc = """
Query the Ubuntu archives and private PPAs for kernel source package
information and print the data in an 'rmadison'-like format.

For regular distribution packages, the standard Ubuntu archive is queried. For
special kernel packages like ESM or private packages, the relevant private PPAs
are queried.

Note: That the user who runs this script needs to have sufficient Launchpad
privileges to query the various private PPAs.
"""

    epilog = """
Examples:
  $ cranky-rmadison bionic:linux
      Print information for the source packages that make up the set of Bionic
      linux kernel packages.

  $ cranky-rmadison -e -a bionic:linux-ibm-gt
      Print all information from all archives and PPAs.
"""

    parser = argparse.ArgumentParser(description=desc, formatter_class=
                                     argparse.RawDescriptionHelpFormatter,
                                     epilog=epilog)
    parser.add_argument("handle", nargs='?', help="A kernel package handle "
                        "in the form of <series>:<source>. If not specified, "
                        "the information is retrieved from the current git "
                        "repo.")
    parser.add_argument("-a", "--show-all", action="store_true",
                        help="Show source package information from all "
                        "routing destinations.")
    parser.add_argument("-e", "--show-extended", action="store_true",
                        help="Show extendend source package information in "
                        "addition to the standard rmadison data")
    args = parser.parse_args()

    try:
        handle_set = Handle().lookup_set(args.handle if args.handle else
                                         os.getcwd(), validate=False)
    except HandleError as e:
        cerror(e)
        sys.exit(1)

    # Query the Launchpsd PPAs for the packages referenced by the provided
    # handle and print the result in an 'rmadison'-like table
    print_table(rmadison_lp(handle_set, show_all=args.show_all),
                show_ext=args.show_extended)
