#!/bin/bash

# TODO:
#  - error handling
#  - parameters
#  - config for mapping 'bionic/main' -> git2/ubuntu-bionic
#  - -v needs to be something ... sometimes


set +x

create_chroot()
{
	local series="$1"
	local arch="$2"

	local chroot="$series-$arch"

	# Validate the chroot.
	schroot -c "$chroot" /bin/true >/dev/null 2>&1 && {
		echo "II: $chroot available"
		RET="$chroot"
		return
	}

	# Create the base chroot.
	echo "II: $chroot needed -- creating"

	mk-sbuild --skip-updates --skip-proposed --distro="ubuntu" --arch="$arch" "$series" </dev/null
	sudo sed -i -e 's/^profile=sbuild/profile=default/g' "/etc/schroot/chroot.d/sbuild-$series-$arch"

	RET="$chroot"
}

create_session()
{
	local series="$1"
	local arch="$2"
	local package="$3"

	local session="srcpkg-$series-$arch-$package"

	# Validate the session.
	schroot -r -c "$session" /bin/true >/dev/null 2>&1 && {
		echo "II: $session available"
		RET="$session"
		return
	}

	# Validate the chroot.
	create_chroot "$series" "$arch"
	local chroot="$RET"

	# Create the base session.
	echo "II: $session needed -- creating"

	schroot -b -n "$session" -c "$chroot"

	schroot -u root -r -c "$session" -- apt-get update
	schroot -u root -r -c "$session" -- apt-get -y -o APT::Get::Only-Source=true build-dep --no-install-recommends "$package"
	schroot -u root -r -c "$session" -- apt-get -y install fakeroot
	
	RET="$session"
}

update_session() {
	local series="$1"
	local arch="$2"
	local package="$3"

	create_session "$series" "$arch" "$package"
	local session="$RET"

	schroot -u root -r -c "$session" -- apt-get update
	schroot -u root -r -c "$session" -- apt-get -y dist-upgrade
}

build_src()
{
	local dir="$1"
	local session="$2"
	
	(
		cd "$dir" || exit 1

		git clean -x -f -d
		schroot -r -c "$session" -- fakeroot debian/rules clean
		schroot -r -c "$session" -- dpkg-buildpackage -S -i -I -uc -us -d
	)
}

series='bionic'
arch='amd64'
sources='bionic bionic-signed bionic-meta'

# Ensure we have the updated session.
update_session "$series" "$arch" "linux"
session="$RET"

# Build the source.
for source in $sources
do
	build_src "$source" "$session"
done
