#!/bin/bash

cranky=$(readlink -f "$0")
cranky_root=$(dirname "$cranky")

if [ "$#" -lt 1 ]; then
	echo "Usage: $cranky <cmd> ..." 1>&2
	exit 1
fi
cmd="$1"
shift

if ! [ -f "$cranky_root/cmds.d/$cmd" ]; then
	echo "$cranky: $cmd: command unknown" 1>&2
	exit 1
fi

C="$cranky" P="cranky $cmd" exec "$cranky_root/cmds.d/$cmd" "$@"
