#!/usr/bin/python3

import os
import sys
import argparse

from crl.config import Config
from crl.handle import Handle, HandleError

def handle_to_series_source(args):
    try:
        handle = Handle().lookup_set(args.handle, validate=False)
    except HandleError as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)

    print(handle.series.codename, handle.source.name)

def series_codename(args):
    try:
        handle = Handle().lookup_set(args.handle)
    except HandleError as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)

    print(handle.series.codename)

def source_packages_path(args):
    try:
        handle = Handle().lookup_set(args.handle)
    except HandleError as e:
        print(str(e), file=sys.stderr)
        sys.exit(1)
    for tree in handle.trees:
        print(tree.directory)

def print_configs(args):
    # Lookup the config options for the given command
    config = Config().lookup(args.command, {})
    if args.key:
        # Print the specified config key
        if args.key in config:
            print(config[args.key])
    else:
        # Print all configs
        for key in sorted(config):
            print("{}: {}".format(key, config[key]))


if __name__ == "__main__":
    desc = """
Helper program for getting cranky config and handle data from shell scripts.
"""
    parser = argparse.ArgumentParser(description=desc, formatter_class=
                                     argparse.RawDescriptionHelpFormatter)
    subparsers = parser.add_subparsers(help="commands", dest="command")
    subparsers.required = True

    # series-codename subparser
    subparser = subparsers.add_parser("handle-to-series-source",
                                      help="Print series codename and source name for the given handle")
    subparser.add_argument("handle",
                           help="<series>:<package> handle, or path to source tree.")
    subparser.set_defaults(func=handle_to_series_source)

    # series-codename subparser
    sc_subparser = subparsers.add_parser("series-codename",
                                           help="Print series codename for the given handle")
    sc_subparser.add_argument("handle",
                               help="<series>:<package> handle, or path to source tree.")
    sc_subparser.set_defaults(func=series_codename)

    # source-packages-path subparser
    spp_subparser = subparsers.add_parser("source-packages-path",
                                          help="Print source packages' paths")
    spp_subparser.add_argument("handle",
                               help="<series>:<package> handle, or path to source tree.")
    spp_subparser.set_defaults(func=source_packages_path)

    # cranky-<foo> config options subparser
    for command in ("clone", "test-build"):
        spp_subparser = subparsers.add_parser(command,
                                              help="Print config options for cranky-%s" % command)
        spp_subparser.add_argument("key", nargs='?', help="Print only the specified config key")
        spp_subparser.set_defaults(func=print_configs)

    args = parser.parse_args()
    args.func(args)
