#!/bin/bash
#
# cranky update-configs -- update configuration in this tree using an appropriate
#                          chroot environment with the cross-compilers installed.
#
C=${C-cranky}
P=${P-$0}

here=$(dirname "$(readlink -f "${0}")")

usage()
{
	cat <<EOF
Usage: cranky update-configs

Update the configuration for this tree using an appropriatly configured
chroot.  When that does not exist tell the user how to make it.
EOF

	exit 2
}

# MAIN:
while [ "$1" ]
do
	case "$1" in
	-*)
		usage
		;;
	*)
		break;
	esac
	shift
done

case "$#" in
0)
	;;
*)
	usage
	;;
esac

handle="."

series_source=$( "$here/cranky-shell-helper" "handle-to-series-source" "$handle" )
if [ "$series_source" = "" ]; then
	echo "$0: $handle: unknown series/package" 1>&2
	exit 1
fi

session=$("$here/cranky" chroot map-session configs "$handle")
if [ "$session" = '' ]; then
	echo "$P: config session not available -- run: $C chroot create-session configs \"$handle\""
	exit 1
fi

schroot -r -c "$session" -- fakeroot debian/rules updateconfigs
