#!/bin/bash
#
# cranky-helper-wrapper
#
C=${C-cranky}
P=${P-$0}

here=$(dirname "$(realpath -e "${0}")")

cmd=${0##*cranky-}

if [ ! -d debian ]; then
	echo "$P: should be run in a source package tree" 1>&2
	exit 1
fi

SCRIPTS="debian/scripts/helpers/$cmd $here/master-helpers/$cmd"
if [ -f debian/debian.env ] ; then
	source debian/debian.env
	SCRIPTS="$DEBIAN/scripts/helpers/$cmd $SCRIPTS"
fi

script=""
for s in $SCRIPTS; do
	if [ -x "$s" ] ; then
		script="$s"
		break;
	fi
done

if [ -z "$script" ] ; then
	echo "$0: $cmd: helper not found" 1>&2
	exit 1
fi

C="$0" P="cranky $cmd" exec "$script" "$@"
