#!/usr/bin/python3

import operator
import sys
import json
from urllib.request import urlopen

(series, package, url) = sys.argv[1:]

if url.endswith(".html"):
    url = url[:-5] + ".latest.json"

with urlopen(url) as response:
    data = json.loads(str(response.read(), 'utf-8'))

#(package, version) = (data['package'], data['version'])
version='0'

print("version %s %s %s \"seed version\"" % (series, package, version))

tests_info = data['tests']
for test_package, package_info in sorted(tests_info.items(), key=operator.itemgetter(0)):
    for arch, result in sorted(package_info.items(), key=operator.itemgetter(0)):
        status = result['status'];
        if status in ('REGN', 'REGR', 'SKIP', 'MISS'):
            status = 'GOOD'
        print("result %s %s %s %s %s %s \"seed version\"" % (series, package, version, test_package, arch, status))
