#!/usr/bin/python3
from __future__     import print_function

import operator
import sys
import json
from urllib.request import urlopen

if len(sys.argv) < 3:
    print("Usage: adt-gen-seed <series> <package-meta> <seed-url> [<sample-url>]", file=sys.stderr)


(series, package, url, sample_url) = (sys.argv[1:] + [None])[:4]

sample_info = None
if sample_url is not None:
    if sample_url.endswith(".html"):
        sample_url = sample_url[:-5] + ".latest.json"

    with urlopen(sample_url) as response:
        sample_data = json.loads(str(response.read(), 'utf-8'))
    sample_info = sample_data['tests']

if url.endswith(".html"):
    url = url[:-5] + ".latest.json"

with urlopen(url) as response:
    data = json.loads(str(response.read(), 'utf-8'))

#(package, version) = (data['package'], data['version'])
version='0'

print("version %s %s %s \"seed version\"" % (series, package, version))

tests_info = data['tests']
for test_package, package_info in sorted(tests_info.items(), key=operator.itemgetter(0)):
    if sample_info is not None and test_package not in sample_info:
        continue
    for arch, result in sorted(package_info.items(), key=operator.itemgetter(0)):
        if sample_info is not None and arch not in sample_info[test_package]:
            continue
        status = result['status'];
        if status in ('REGN', 'REGR', 'SKIP', 'MISS'):
            status = 'GOOD'

        print("result %s %s %s %s %s %s \"seed version\"" % (series, package, version, test_package, arch, status))
